parameters:
    dothiv.api.controller.attachment.class: Dothiv\APIBundle\Controller\AttachmentController
    dothiv.api.controller.account.class: Dothiv\APIBundle\Controller\AccountController
    dothiv.api.controller.user.class: Dothiv\APIBundle\Controller\UserController
    dothiv.api.controller.crud.class: Dothiv\APIBundle\Controller\CRUDController

services:
    dothiv.api.controller.domain:
        class: Dothiv\APIBundle\Controller\DomainController
        arguments:
         - @security.context
         - @dothiv.repository.domain
         - @dothiv.repository.domainclaim
         - @serializer
         - @dothiv.business.event_dispatcher
         - @clock

    dothiv.api.controller.banner:
        class: Dothiv\APIBundle\Controller\BannerController
        arguments:
         - @security.context
         - @dothiv.repository.domain
         - @dothiv.repository.banner
         - @validator
         - @serializer

    dothiv.api.controller.user:
        class: %dothiv.api.controller.user.class%
        arguments:
         - @security.context
         - @dothiv.repository.domain
         - @dothiv.repository.user
         - @dothiv.repository.user_token
         - @serializer
         - @clock
         - @dothiv.businessbundle.service.user

    dothiv.api.controller.account:
        class: %dothiv.api.controller.account.class%
        arguments:
         - @dothiv.businessbundle.service.user
         - @dothiv.repository.user
         - @serializer
         - @clock

    dothiv.api.controller.attachment:
        class: %dothiv.api.controller.attachment.class%
        arguments:
         - @dothiv.businessbundle.service.attachment
         - @security.context
         - @serializer

    dothiv.api.controller.nonprofit:
        class: Dothiv\APIBundle\Controller\NonProfitRegistrationController
        arguments:
         - @dothiv.repository.nonprofitregistration
         - @dothiv.repository.attachment
         - @security.context
         - @serializer

    dothiv.api.controller.user_notification:
        class: %dothiv.api.controller.crud.class%
        arguments:
        - @dothiv.repository.user_notification
        - @dothiv.api.transformer.user_notification
        - @dothiv.admin.transformer.paginatedlist
        - @serializer
        - @dothiv.repository.entity_change
        - @security.context
        - @dothiv.api.manipulator.generic
        calls:
        - [disableHistory]
