parameters:
    dothiv.api.controller.attachment.class: Dothiv\APIBundle\Controller\AttachmentController
    dothiv.api.controller.account.class: Dothiv\APIBundle\Controller\AccountController

services:
    dothiv.api.controller.domain:
        class: Dothiv\APIBundle\Controller\DomainController
        arguments:
         - @security.context
         - @dothiv.repository.domain
         - @dothiv.repository.domainclaim
         - @serializer
         - @event_dispatcher
         - @clock

    dothiv.api.controller.banner:
        class: Dothiv\APIBundle\Controller\BannerController
        arguments:
         - @security.context
         - @dothiv.repository.domain
         - @dothiv.repository.banner
         - @validator
         - @serializer

    dothiv.api.controller.user:
        class: Dothiv\APIBundle\Controller\UserController
        arguments:
         - @security.context
         - @dothiv.repository.domain
         - @dothiv.repository.user
         - @dothiv.repository.user_token
         - @serializer
         - @clock

    dothiv.api.controller.account:
        class: %dothiv.api.controller.account.class%
        arguments:
         - @dothiv.businessbundle.service.user
         - @dothiv.repository.user
         - @serializer
         - @clock

    dothiv.api.controller.attachment:
        class: %dothiv.api.controller.attachment.class%
        arguments:
         - @dothiv.businessbundle.service.attachment
         - @security.context
         - @serializer

    dothiv.api.controller.nonprofit:
        class: Dothiv\APIBundle\Controller\NonProfitRegistrationController
        arguments:
         - @dothiv.repository.nonprofitregistration
         - @dothiv.repository.attachment
         - @security.context
         - @serializer
