dothiv_api_domain_claim:
    pattern:  /domain/claim
    defaults:
        _controller: dothiv.api.controller.domain:claimAction
        _format: json
    methods: [POST]

dothiv_api_domain_claim_notoken:
    pattern:  /domain/{name}/claim
    defaults:
        _controller: dothiv.api.controller.domain:claimNoTokenAction
        _format: json
    methods: [PUT]

dothiv_api_attachment:
    pattern:  /attachment
    defaults:
        _controller: dothiv.api.controller.attachment:createAction
        _format: json
    methods: [POST]

dothiv_api_nonprofit_load:
    pattern:  /nonprofit/{name}
    defaults:
        _controller: dothiv.api.controller.nonprofit:loadAction
        _format: json
    methods: [GET]

dothiv_api_nonprofit_update:
    pattern:  /nonprofit/{name}
    defaults:
        _controller: dothiv.api.controller.nonprofit:updateAction
        _format: json
    methods: [PUT]

dothiv_api_user_profile:
    pattern:  /user/{handle}
    defaults:
        _controller: dothiv.api.controller.user:profileAction
        _format: json
    methods: [GET]

dothiv_api_user_profile_update:
    path: /user/{handle}
    defaults:
        _controller: dothiv.api.controller.user:updateProfileAction
        _format: json
    methods: [PATCH]

dothiv_api_user_token:
    pattern:  /user/{handle}/token
    defaults:
        _controller: dothiv.api.controller.user:revokeTokenAction
        _format: json
    methods: [DELETE]

dothiv_api_user_domains:
    pattern:  /user/{handle}/domains
    defaults:
        _controller: dothiv.api.controller.user:domainsAction
        _format: json
    methods: [GET]

dothiv_api_domain_banner_config_set:
    pattern:  /domain/{name}/banner
    defaults:
        _controller: dothiv.api.controller.banner:setConfigAction
        _format: json
    methods: [PUT]

dothiv_api_domain_banner_config_get:
    pattern:  /domain/{name}/banner
    defaults:
        _controller: dothiv.api.controller.banner:getConfigAction
        _format: json
    methods: [GET]

dothiv_api_account_create:
    pattern:  /account
    defaults:
        _controller: dothiv.api.controller.account:createAction
        _format: json
    methods: [POST]

dothiv_api_account_loginlink:
    pattern:  /account/loginLink
    defaults:
        _controller: dothiv.api.controller.account:loginLinkAction
        _format: json
    methods: [POST]

## User notifications
dothiv_api_user_notification:
    pattern:  /user/{handle}/notification/{identifier}
    defaults:
        _controller: dothiv.api.controller.user_notification:getItemAction
        _format: json
    methods: [GET]

dothiv_api_user_notification_list:
    pattern:  /user/{handle}/notification
    defaults:
        _controller: dothiv.api.controller.user_notification:listItemsAction
        _format: json
    methods: [GET]

dothiv_api_user_notification_update:
    path: /user/{handle}/notification/{identifier}
    defaults:
        _controller: dothiv.api.controller.user_notification:updateItemAction
        _format: json
    methods: [PATCH]

## User profile change
dothiv_api_user_profile_change:
    pattern:  /user/{handle}/profile_change/{identifier}
    defaults:
        _controller: dothiv.api.controller.user_profile_change:getItemAction
        _format: json
    methods: [GET]

dothiv_api_user_profile_change_update:
    pattern:  /user/{handle}/profile_change/{identifier}
    defaults:
        _controller: dothiv.api.controller.user_profile_change:updateItemAction
        _format: json
    methods: [PATCH]
