parameters:
    dothiv.api.transformer.user_notification.class: Dothiv\APIBundle\Transformer\UserNotificationTransformer
    dothiv.api.manipulator.generic.class: Dothiv\APIBundle\Manipulator\GenericEntityManipulator

services:
    dothiv.api.manipulator.generic:
        class: %dothiv.api.manipulator.generic.class%

    dothiv.api.transformer.user_notification:
        class: %dothiv.api.transformer.user_notification.class%
        arguments:
        - @router
        - "dothiv_api_user_notification"
