parameters:
    dothiv.api.transformer.user_notification.class: Dothiv\APIBundle\Transformer\UserNotificationTransformer
    dothiv.api.transformer.user_profile_change.class: Dothiv\APIBundle\Transformer\UserProfileChangeTransformer
    dothiv.api.transformer.domain.class: Dothiv\APIBundle\Transformer\DomainTransformer
    dothiv.api.transformer.user.class: Dothiv\APIBundle\Transformer\UserTransformer
    dothiv.api.transformer.user_token.class: Dothiv\APIBundle\Transformer\UserTokenTransformer
    dothiv.api.manipulator.generic.class: Dothiv\APIBundle\Manipulator\GenericEntityManipulator
    dothiv.api.manipulator.user_profile_change.class: Dothiv\APIBundle\Manipulator\UserProfileChangeEntityManipulator
    dothiv.api.user_token.class: Dothiv\APIBundle\Factory\UserTokenFactory

services:
    dothiv.api.manipulator.generic:
        class: %dothiv.api.manipulator.generic.class%

    dothiv.api.transformer.user_notification:
        class: %dothiv.api.transformer.user_notification.class%
        arguments:
        - @router
        - "dothiv_api_user_notification"

    dothiv.api.manipulator.user_profile_change:
        class: %dothiv.api.manipulator.user_profile_change.class%

    dothiv.api.transformer.user_profile_change:
        class: %dothiv.api.transformer.user_profile_change.class%
        arguments:
        - @router
        - "dothiv_api_user_profile_change"

    dothiv.api.transformer.domain:
        class: %dothiv.api.transformer.domain.class%
        arguments:
        - @router
        - "dothiv_api_domain"

    dothiv.api.transformer.user:
        class: %dothiv.api.transformer.user.class%
        arguments:
        - @router
        - "dothiv_api_user_profile"

    dothiv.api.transformer.user_token:
        class: %dothiv.api.transformer.user_token.class%
        arguments:
        - @router
        - "dothiv_api_user_token"

    dothiv.api.user_token.factory.api:
        class: %dothiv.api.user_token.class%
        arguments:
        - @clock
        - "api"
        - 1800
