parameters:
    dothiv.websitebase.contentful.content.class: Dothiv\BaseWebsiteBundle\Contentful\Content
    dothiv.websitebase.contentful.view_builder.class: Dothiv\BaseWebsiteBundle\Contentful\ViewBuilder
    dothiv.websitebase.contentful.image_scaler.class: Dothiv\BaseWebsiteBundle\Contentful\ImageAssetScaler
    dothiv.websitebase.service.money_format.class: Dothiv\BaseWebsiteBundle\Service\MoneyFormatService
    dothiv.websitebase.service.number_format.class: Dothiv\BaseWebsiteBundle\Service\NumberFormatService
    dothiv.websitebase.imagine.class: Imagine\Gmagick\Imagine
    dothiv.websitebase.service.image_scaler.class: Dothiv\BaseWebsiteBundle\Service\ImagineImageScaler

services:
    dothiv.websitebase.contentful.view_builder:
            class: %dothiv.websitebase.contentful.view_builder.class%
            arguments:
                - 'en'
                - @dothiv_contentful.content
                - @dothiv.business.event_dispatcher

    dothiv.websitebase.contentful.image_scaler:
        class: %dothiv.websitebase.contentful.image_scaler.class%
        arguments:
            - 'en'
            - @dothiv_contentful.asset
            - @dothiv.websitebase.service.image_scaler

    dothiv.websitebase.imagine:
        class: %dothiv.websitebase.imagine.class%
        lazy: true

    dothiv.websitebase.service.image_scaler:
        class: %dothiv.websitebase.service.image_scaler.class%
        lazy: true
        arguments:
          - @dothiv.websitebase.imagine

    dothiv.websitebase.cache.request_lastmodified:
        class: Dothiv\BaseWebsiteBundle\Cache\RequestLastModifiedCache
        arguments:
         - @doctrine_cache.providers.dothiv_base_website_cache
         - @dothiv.repository.config
        tags:
         - { name: dothiv.business.event_listener, event: dothiv.basewebsite.contentful.view.create, method: onViewCreate }
         - { name: kernel.event_listener, event: contentful.entry.sync, method: onEntryUpdate }
        calls:
         - [ setLogger, [@logger] ]

    dothiv.websitebase.number_format:
        class: %dothiv.websitebase.service.number_format.class%

    dothiv.websitebase.money_format:
        class: %dothiv.websitebase.service.money_format.class%
        arguments:
        - @dothiv.websitebase.number_format
