parameters:
    dothiv.websitebase.assetic.filter.ngmin.class: Dothiv\BaseWebsiteBundle\Assetic\Filter\NgMinFilter
    dothiv.websitebase.contentful.content.class: Dothiv\BaseWebsiteBundle\Contentful\Content
    dothiv.websitebase.contentful.view_builder.class: Dothiv\BaseWebsiteBundle\Contentful\ViewBuilder
    dothiv.websitebase.contentful.image_scaler.class: Dothiv\BaseWebsiteBundle\Contentful\ImageAssetScaler
    dothiv.websitebase.service.money_format.class: Dothiv\BaseWebsiteBundle\Service\MoneyFormatService
    dothiv.websitebase.imagine.class: Imagine\Gmagick\Imagine
    dothiv.websitebase.service.image_scaler.class: Dothiv\BaseWebsiteBundle\Service\ImagineImageScaler

services:
    dothiv.websitebase.assetic.filter.ngmin:
        class: %dothiv.websitebase.assetic.filter.ngmin.class%
        tags:
            - { name: assetic.filter, alias: ngmin }
        arguments: [%ngmin_bin%]

    dothiv.websitebase.assetic.filter.closureecma5:
        class: %assetic.filter.closure.jar.class%
        tags:
            - { name: assetic.filter, alias: closureecma5 }
        arguments: [%assetic.filter.closure.jar%, %assetic.filter.closure.java%]
        calls:
            - [ setTimeout, [%assetic.filter.closure.timeout%] ]
            - [ setCompilationLevel, [%assetic.filter.closure.compilation_level%] ]
            - [ setLanguage, ['ECMASCRIPT5'] ]
            
    dothiv.websitebase.contentful.view_builder:
            class: %dothiv.websitebase.contentful.view_builder.class%
            arguments:
                - 'en'
                - @dothiv_contentful.content
                - @event_dispatcher

    dothiv.websitebase.contentful.image_scaler:
        class: %dothiv.websitebase.contentful.image_scaler.class%
        arguments:
            - 'en'
            - @dothiv_contentful.asset
            - @dothiv.websitebase.service.image_scaler

    dothiv.websitebase.imagine:
        class: %dothiv.websitebase.imagine.class%
        lazy: true

    dothiv.websitebase.service.image_scaler:
        class: %dothiv.websitebase.service.image_scaler.class%
        lazy: true
        arguments:
          - @dothiv.websitebase.imagine

    dothiv.websitebase.cache.request_lastmodified:
        class: Dothiv\BaseWebsiteBundle\Cache\RequestLastModifiedCache
        arguments:
         - @doctrine_cache.providers.dothiv_base_website_cache
         - @dothiv.repository.config
        tags:
         - { name: kernel.event_listener, event: dothiv.basewebsite.contentful.view.create, method: onViewCreate }
         - { name: kernel.event_listener, event: contentful.entry.sync, method: onEntryUpdate }
        calls:
         - [ setLogger, [@logger] ]

    dothiv.websitebase.money_format:
        class: %dothiv.websitebase.service.money_format.class%
