services:
    dothiv_hiv_domain_status.api.controller.domain_check:
        class: %dothiv.api.controller.crud.class%
        arguments:
        - @dothiv_hiv_domain_status.repository.check
        - @dothiv_hiv_domain_status.api.transformer.domain_check
        - @dothiv.admin.transformer.paginatedlist
        - @serializer
        - @dothiv.repository.entity_change
        - @security.context
        - @dothiv.api.manipulator.generic
        - @dothiv.business.event_dispatcher
        calls:
        - [disableHistory]
