parameters:
    dothiv_hiv_domain_status.service.class: Dothiv\HivDomainStatusBundle\Service\GuzzleService
    dothiv_hiv_domain_status.service.client.class: Guzzle\Http\Client

services:
    dothiv_hiv_domain_status.service.client:
        class: %dothiv_hiv_domain_status.service.client.class%

    dothiv_hiv_domain_status.service:
        class: %dothiv_hiv_domain_status.service.class%
        arguments:
        - @dothiv_hiv_domain_status.service.client
        - @dothiv.business.event_dispatcher
        - %dothiv_hiv_domain_status.endpoint%
