dothiv_landingpageconfig_preview:
    host: %charitydomain%
    schemes:  [https]
    path:     /{locale}/landingpage-configurator/{domain}/preview
    defaults:
        _controller: dothiv.landingpage.controller.preview:previewAction
    requirements:
        locale: ^(en|de|ky)$

dothiv_landingpageconfig_page:
    host: %charitydomain%
    schemes:  [https]
    path:     /{locale}/landingpage-configurator/{domain}/{appstate}
    defaults:
        _controller: dothiv.landingpage.controller.page:pageAction
        page: landingpage.configurator
        template: Configurator:start
        appstate: ~
    requirements:
        locale: ^(en|de|ky)$
        appstate: .+
