parameters:
    dothiv.landingpage.genitivfy.class: Dothiv\LandingpageBundle\Service\GenitivfyService
    dothiv.landingpage.service.class: Dothiv\LandingpageBundle\Service\LandingpageService
    dothiv.landingpage.config.class: Dothiv\LandingpageBundle\Service\LandingpageConfigService
    dothiv.landingpage.transformer.landingpage_configuration.class: Dothiv\LandingpageBundle\Transformer\LandingpageConfigurationTransformer

services:
    dothiv.landingpage:
        class: %dothiv.landingpage.service.class%
        arguments:
        - @dothiv.repository.landingpage_configuration

    dothiv.landingpage.genitivfy:
        class: %dothiv.landingpage.genitivfy.class%

    dothiv.landingpage.content:
        class: %dothiv.websitebase.contentful.content.class%
        arguments:
        - @dothiv_contentful.content
        - @dothiv.websitebase.contentful.view_builder
        - %contenful_space_landingpage%

    dothiv.landingpage.config:
        class: %dothiv.landingpage.config.class%
        arguments:
        - @dothiv.landingpage.content
        - %dothiv_business.clickcounter%
        - @dothiv.landingpage.genitivfy

    dothiv.landingpage.transformer.landingpage_configuration:
        class: %dothiv.landingpage.transformer.landingpage_configuration.class%
        arguments:
        - @router
        - "dothiv_landingpageconfig_config"
