services:
    dothiv.registry.web.controller.page:
        class: Dothiv\RegistryWebsiteBundle\Controller\PageController
        arguments:
          - @dothiv.websitebase.cache.request_lastmodified
          - @templating
          - @dothiv.registry.contentful.registry_content
          - "DothivRegistryWebsiteBundle"
          - %assets_version%
          - @clock
          - %page_lifetime%

    dothiv.registry.api.controller:
        class: Dothiv\RegistryWebsiteBundle\Controller\ApiController
        arguments:
          - @mailer

    dothiv.registry.web.controller.app:
        class: Dothiv\BaseWebsiteBundle\Controller\AppController
        arguments:
          - @dothiv.websitebase.cache.request_lastmodified
          - @templating
          - @dothiv.registry.contentful.registry_content
          - "DothivRegistryWebsiteBundle"
          - %assets_version%
          - @clock
          - %page_lifetime%

    dothiv.registry.web.controller.premiumBid:
        class: Dothiv\RegistryWebsiteBundle\Controller\PremiumBidController
        arguments:
        - @dothiv.repository.premiumbid
