services:
    dothiv.registry.web.contentful.registry_image_listener:
        class: %dothiv.base.web.contentul.image_listener.class%
        arguments:
            - @dothiv.websitebase.contentful.image_scaler
            - 'Registrar'
            - 'image'
        tags:
            - { name: dothiv.business.event_listener, event: dothiv.basewebsite.contentful.view.create, method: onViewCreate }
