# Redirect to default locale: en
dothiv_registry_index_nolang:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /en
        permanent: true

dothiv_registry_api_preregister:
    pattern:  /api/preregister
    defaults:
        _controller: dothiv.registry.api.controller:preregisterAction
    methods:  [POST]

dothiv_register_nonprofit_form:
    pattern:  /{locale}/register-non-profit-form
    defaults:
        _controller: dothiv.registry.web.controller.page:pageAction
        page: register-non-profit-form
    requirements:
        locale:  en|ky

dothiv_registry_content_api:
    pattern:  /{locale}/content/{type}
    defaults:
        _controller: dothiv.registry.web.controller.page:contentAction
    requirements:
        locale:  en
        type: Registrar|hivDomain

dothiv_registry_app_template:
    pattern:  /{locale}/app/{section}/{page}.{_format}
    defaults:
        _controller: dothiv.registry.web.controller.app:templateAction
    requirements:
        _format:  html
        locale:  en|de|ky

dothiv_registry_content:
    pattern:  /{locale}/c/{page}
    defaults:
        _controller: dothiv.registry.web.controller.page:contentPageAction
    requirements:
        locale:  en|ky
        page: ^([a-zA-Z][a-zA-Z0-9]*[/-])*[a-zA-Z][a-zA-Z0-9]*$

dothiv_registry_page:
    pattern:  /{locale}/{page}
    defaults:
        _controller: dothiv.registry.web.controller.page:pageAction
        page: index
    requirements:
        locale:  en|ky

dothiv_registry_report:
    pattern:  /{locale}/report
    defaults:
        _controller: dothiv.registry.web.controller.page:pageAction
        page: report
    requirements:
        locale:  en|ky

dothiv_registry_sedo:
    path: /api/premiumbid
    defaults:
        _controller: dothiv.registry.web.controller.premiumBid:createBidAction
        _format: json
