parameters:
    dothiv.registry.service.mailer.login.class: Dothiv\BaseWebsiteBundle\Service\Mailer\LoginLinkMailer
    dothiv.registry.service.mailer.nonprofitregistration.class: Dothiv\RegistryWebsiteBundle\Service\Mailer\NonProfitRegistrationMailer
    dothiv.registry.service.mailer.content.class: Dothiv\BaseWebsiteBundle\Service\Mailer\ContentMailer
services:
    dothiv.registry.translation.strings_loader:
        class: Dothiv\BaseWebsiteBundle\Translation\ContentfulStringsLoader
        arguments:
         - @dothiv.registry.contentful.registry_content
         - 'String'
         - 'ky'
        tags:
         - { name: translation.loader, alias: contentful_strings_registry }

    dothiv.registry.contentful.registry_content:
        class: %dothiv.websitebase.contentful.content.class%
        arguments:
            - @dothiv_contentful.content
            - @dothiv.websitebase.contentful.view_builder
            - %contenful_space_registry%

    dothiv.registry.service.mailer.login:
        class: %dothiv.registry.service.mailer.login.class%
        arguments:
        - @dothiv.registry.service.mailer.content
        - @router
        - 'dothiv_register_nonprofit_form'
        - %registrydomain%
        - @dothiv.businessbundle.service.user
        tags:
            - { name: kernel.event_listener, event: dothiv.business.user.loginlink.requested, method: onLoginLinkRequested }

    dothiv.registry.service.mailer.content:
        class: %dothiv.registry.service.mailer.content.class%
        arguments:
        - @mailer
        - @dothiv.registry.contentful.registry_content
        - @dothiv_contentful.asset
        - @dothiv_contentful.repo.asset
        - %email_from_address%
        - %email_from_name%

    dothiv.registry.service.mailer.nonprofitregistration:
        class: %dothiv.registry.service.mailer.nonprofitregistration.class%
        arguments:
        - @dothiv.registry.service.mailer.content
