# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:
      - 'DothivCharityWebsiteBundle'
      - 'DothivRegistryWebsiteBundle'
      - 'DothivAPIBundle'
      - 'DothivAngularJsBundle'
      - 'DothivPremiumConfiguratorBundle'
      - 'DothivAdminBundle'
      - 'DothivPayitforwardBundle'
      - 'DothivDomainGiftBundle'
    #java: /usr/bin/java
    filters:
        less:
            node: %node_bin%
            node_paths: [%node_modules%]
            apply_to: "\.less$"
        cssrewrite: ~
        uglifyjs2:
            bin: "%kernel.root_dir%/../node_modules/uglify-js/bin/uglifyjs"
        uglifycss:
            bin: "%kernel.root_dir%/../node_modules/uglifycss/uglifycss"
    assets:
        punycode_js:
            inputs:
            - %kernel.root_dir%/../vendor/components/bestiejs-punycode/punycode.js
        angular_js:
            inputs:
            - %kernel.root_dir%/../vendor/components/angularjs/angular.js
        angular_js_resource:
            inputs:
            - %kernel.root_dir%/../vendor/components/angularjs/angular-resource.js
        angular_js_route:
            inputs:
            - %kernel.root_dir%/../vendor/components/angularjs/angular-route.js
        angular_js_cookies:
            inputs:
            - %kernel.root_dir%/../vendor/components/angularjs/angular-cookies.js
        angular_ui_router:
            inputs:
            - %kernel.root_dir%/../vendor/components/angular-ui-router/release/angular-ui-router.js
        angular_ui_bootstrap:
            inputs:
            - %kernel.root_dir%/../vendor/components/bootstrap/ui-bootstrap.js
        angular_ui_bootstrap_tpls:
            inputs:
            - %kernel.root_dir%/../vendor/components/bootstrap/ui-bootstrap-tpls.js
        angular_file_upload:
            inputs:
            - %kernel.root_dir%/../vendor/components/nervgh-angular-file-upload/angular-file-upload.js
        bootstrap_glyphicons_woff:
            inputs:
            - %kernel.root_dir%/../vendor/twitter/bootstrap/fonts/glyphicons-halflings-regular.woff
            output: css/fonts/glyphicons-halflings-regular.woff
        bootstrap_glyphicons_ttf:
            inputs:
            - %kernel.root_dir%/../vendor/twitter/bootstrap/fonts/glyphicons-halflings-regular.ttf
            output: css/fonts/glyphicons-halflings-regular.ttf
        bootstrap_js:
            inputs:
            - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/js/bootstrap.js
        bootstrap_js_collapse:
            inputs:
            - %kernel.root_dir%/../vendor/twitter/bootstrap/js/collapse.js
        registryicons_svg:
            inputs:
            - %kernel.root_dir%/../src/Dothiv/RegistryWebsiteBundle/Resources/public/fonts/registryicons.svg
            output: css/fonts/registryicons.svg
        registryicons_woff:
            inputs:
            - %kernel.root_dir%/../src/Dothiv/RegistryWebsiteBundle/Resources/public/fonts/registryicons.woff
            output: css/fonts/registryicons.woff
        registryicons_ttf:
            inputs:
            - %kernel.root_dir%/../src/Dothiv/RegistryWebsiteBundle/Resources/public/fonts/registryicons.ttf
            output: css/fonts/registryicons.ttf
        registryicons_eot:
            inputs:
            - %kernel.root_dir%/../src/Dothiv/RegistryWebsiteBundle/Resources/public/fonts/registryicons.eot
            output: css/fonts/registryicons.eot
        charityicons_svg:
            inputs:
            - %kernel.root_dir%/../src/Dothiv/CharityWebsiteBundle/Resources/public/fonts/charityicons.svg
            output: css/fonts/charityicons.svg
        charityicons_woff:
            inputs:
            - %kernel.root_dir%/../src/Dothiv/CharityWebsiteBundle/Resources/public/fonts/charityicons.woff
            output: css/fonts/charityicons.woff
        charityicons_ttf:
            inputs:
            - %kernel.root_dir%/../src/Dothiv/CharityWebsiteBundle/Resources/public/fonts/charityicons.ttf
            output: css/fonts/charityicons.ttf
        charityicons_eot:
            inputs:
            - %kernel.root_dir%/../src/Dothiv/CharityWebsiteBundle/Resources/public/fonts/charityicons.eot
            output: css/fonts/charityicons.eot
        jquery:
            inputs:
            - %kernel.root_dir%/../vendor/components/jquery/jquery.js
        jquery_mmenu_js:
            inputs:
            - %kernel.root_dir%/../vendor/component/besite-jquery-mmenu/src/js/jquery.mmenu.min.all.js
        jquery_mmenu_css:
            inputs:
            - %kernel.root_dir%/../vendor/component/besite-jquery-mmenu/src/css/jquery.mmenu.all.css
        angular_colorpicker_js:
            inputs:
            - %kernel.root_dir%/../vendor/components/buberdds-angular-bootstrap-colorpicker/js/bootstrap-colorpicker-module.js
        angular_colorpicker_css:
            inputs:
            - %kernel.root_dir%/../vendor/components/buberdds-angular-bootstrap-colorpicker/css/colorpicker.css
        # https://github.com/urish/angular-moment
        angular_moment:
            inputs:
            - %kernel.root_dir%/../vendor/components/moment/moment.js
            - %kernel.root_dir%/../vendor/components/urish-angular-moment/angular-moment.js
        # https://github.com/zeroclipboard/zeroclipboard
        zeroclipboard_js:
            inputs:
            - %kernel.root_dir%/../vendor/zeroclipboard/zeroclipboard/dist/ZeroClipboard.js
        zeroclipboard_swf:
            inputs:
            - %kernel.root_dir%/../vendor/zeroclipboard/zeroclipboard/dist/ZeroClipboard.swf
            output: swf/ZeroClipboard.swf
