imports:
    - { resource: config_dev.yml }
    - { resource: parameters_test.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_test.yml" }
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    orm:
        auto_generate_proxy_classes: true
        auto_mapping: true
    dbal:
        driver:   pdo_sqlite
        host:     ~
        port:     ~
        dbname:   ~
        user:     ~
        password: ~
        path:     "%kernel.root_dir%/cache/test/test.db"
        charset:  UTF8

stof_doctrine_extensions:
    class:
        timestampable: Dothiv\BusinessBundle\Tests\Extra\TimestampableListener

dothiv_business:
    clock_expr: "2014-01-02T13:14:15"

parameters:
    contenful_space_charity: charity_space
    contenful_space_registry: registry_space
    contenful_space_clickcounter: clickcounter_space
    contenful_space_landingpage: landingpage_space
    dothiv.websitebase.imagine.class: Dothiv\BaseWebsiteBundle\Tests\Extra\Imagine
    dothiv.charity.sendwithus_renderer.class: Dothiv\CharityWebsiteBundle\Tests\Extra\NullTemplateRenderer
    dothiv.charity.userreminder.mailer.class: Dothiv\CharityWebsiteBundle\Tests\Extra\NullUserReminderMailer

