# API routing
dothiv_api:
    resource: "@DothivAPIBundle/Resources/config/routing.yml"
    prefix:   /api/

# routing for charity website
dothiv_charity_web:
    resource: .
    type: charity_routes
    host: %charitydomain%
    prefix:   /

# routing for company website
dothiv_registry_web:
    host: %registrydomain%
    resource: "@DothivRegistryWebsiteBundle/Resources/config/routing.yml"
    prefix:   /

# .hiv Domain gifts
dothiv_domain_gift:
    resource: "@DothivDomainGiftBundle/Resources/config/routing.yml"
    prefix: /

# QLP landingpages
dothiv_qlp_partner:
    host: "{partner}.friends.%charitydomain%"
    resource: "@DothivQLPPartnerBundle/Resources/config/routing.yml"
    prefix:   /

# HIV domain iframes
dothiv_domain_iframe:
    host: "{domainname}.iframe.%charitydomain%"
    pattern:  /
    defaults:
        _controller: dothiv.charity.web.controller.iframe:iframeAction

dothiv_domain_iframe_cname:
    host: "www.{domainname}.hiv"
    pattern:  /
    defaults:
        _controller: dothiv.charity.web.controller.iframe:iframeAction

# Contentful Bundle
dothiv_contentful:
    resource: "@DothivContentfulBundle/Resources/config/routing.yml"
    prefix:   /contentful/

# Premium Configurator
dothiv_premium_configurator:
    resource: "@DothivPremiumConfiguratorBundle/Resources/config/routing.yml"
    prefix:   /

# Admin Dashboard
dothiv_admin:
    host: %registrydomain%
    resource: "@DothivAdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

# Pay it forward
dothiv_payitforward:
    host: %registrydomain%
    resource: "@DothivPayitforwardBundle/Resources/config/routing.yml"
    prefix:   /
