security:
    encoders:
        Dothiv\BusinessBundle\Entity\User: bcrypt
        Dothiv\ContentfulBundle\Service\WebhookUser: plaintext

    providers:
        user:
            id: dothiv.businessbundle.service.user
        contentful_webhook:
            id: dothiv_contentful.service.webhook_user

    role_hierarchy:
        ROLE_USER: ~
        ROLE_VOTER:            ROLE_USER
        ROLE_PROJECT_MANAGER:  ROLE_USER
        ROLE_DOMAIN_MANAGER:   ROLE_USER
        ROLE_ADMIN:            [ROLE_VALIDATED, ROLE_PROJECT_MANAGER, ROLE_DOMAIN_MANAGER]
        ROLE_SUPER_ADMIN:      ROLE_ADMIN
        ROLE_CONTENTFUL_WEBHOOK: ~

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user_basicauth:
            pattern:    ^/api/(usertoken)
            stateless:  true
            provider:   user
            http_basic:
                realm: "click4life.hiv API"

        user_oauth:
            pattern:    ^/api/(user|domain|attachment|nonprofit|premium-configurator|payitforward|notification|landingpage)
            stateless:  true
            provider:   user
            oauth2:     true

        admin:
            pattern:    ^/admin/api/(stats|nonprofitregistration|attachment|domain|config|history|registrar|hivdomainstatus|whois)
            stateless:  true
            provider:   user
            oauth2:     true

        contentful_webhook:
            pattern: ^/contentful/webhook
            provider: contentful_webhook
            http_basic:
              realm: "Contentful Webhook Area"

    access_control:
      - { path: ^/api/(usertoken), roles: ROLE_USER }
      - { path: ^/api/(user|domain|attachment|nonprofit|premium-configurator|payitforward|notification|landingpage), roles: ROLE_USER }
      - { path: ^/admin/api, roles: ROLE_ADMIN }
      - { path: ^/contentful/webhook, roles: ROLE_CONTENTFUL_WEBHOOK }
