<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Use ISO codes for shop orders
 */
class Version20150119154359 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("UPDATE ShopOrder SET country = 'AF' WHERE country = 'Afghanistan (‫افغانستان‬‎)' OR country = 'Afghanistan (‫افغانستان‬‎)' OR country = '‫افغانستان‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'AX' WHERE country = 'Åland Islands (Åland)' OR country = 'Åland-Inseln (Åland)' OR country = 'Åland'");
        $this->addSql("UPDATE ShopOrder SET country = 'AL' WHERE country = 'Albania (Shqipëri)' OR country = 'Albanien (Shqipëri)' OR country = 'Shqipëri'");
        $this->addSql("UPDATE ShopOrder SET country = 'DZ' WHERE country = 'Algeria (‫الجزائر‬‎)' OR country = 'Algerien (‫الجزائر‬‎)' OR country = '‫الجزائر‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'AS' WHERE country = 'American Samoa (American Samoa)' OR country = 'Amerikanisch-Samoa (American Samoa)' OR country = 'American Samoa'");
        $this->addSql("UPDATE ShopOrder SET country = 'AD' WHERE country = 'Andorra (Andorra)' OR country = 'Andorra (Andorra)' OR country = 'Andorra'");
        $this->addSql("UPDATE ShopOrder SET country = 'AO' WHERE country = 'Angola (Angola)' OR country = 'Angola (Angola)' OR country = 'Angola'");
        $this->addSql("UPDATE ShopOrder SET country = 'AI' WHERE country = 'Anguilla (Anguilla)' OR country = 'Anguilla (Anguilla)' OR country = 'Anguilla'");
        $this->addSql("UPDATE ShopOrder SET country = 'AQ' WHERE country = 'Antarctica (Antarctica)' OR country = 'Antarktis (Antarctica)' OR country = 'Antarctica'");
        $this->addSql("UPDATE ShopOrder SET country = 'AG' WHERE country = 'Antigua and Barbuda (Antigua and Barbuda)' OR country = 'Antigua und Barbuda (Antigua and Barbuda)' OR country = 'Antigua and Barbuda'");
        $this->addSql("UPDATE ShopOrder SET country = 'AR' WHERE country = 'Argentina (Argentina)' OR country = 'Argentinien (Argentina)' OR country = 'Argentina'");
        $this->addSql("UPDATE ShopOrder SET country = 'AM' WHERE country = 'Armenia (Հայաստան)' OR country = 'Armenien (Հայաստան)' OR country = 'Հայաստան'");
        $this->addSql("UPDATE ShopOrder SET country = 'AW' WHERE country = 'Aruba (Aruba)' OR country = 'Aruba (Aruba)' OR country = 'Aruba'");
        $this->addSql("UPDATE ShopOrder SET country = 'SH-AC' WHERE country = 'Ascension Island (Ascension Island)' OR country = 'Ascension (Ascension Island)' OR country = 'Ascension Island'");
        $this->addSql("UPDATE ShopOrder SET country = 'AU' WHERE country = 'Australia (Australia)' OR country = 'Australien (Australia)' OR country = 'Australia'");
        $this->addSql("UPDATE ShopOrder SET country = 'AT' WHERE country = 'Austria (Österreich)' OR country = 'Österreich (Österreich)' OR country = 'Österreich'");
        $this->addSql("UPDATE ShopOrder SET country = 'AZ' WHERE country = 'Azerbaijan (Azərbaycan)' OR country = 'Aserbaidschan (Azərbaycan)' OR country = 'Azərbaycan'");
        $this->addSql("UPDATE ShopOrder SET country = 'BS' WHERE country = 'Bahamas (Bahamas)' OR country = 'Bahamas (Bahamas)' OR country = 'Bahamas'");
        $this->addSql("UPDATE ShopOrder SET country = 'BH' WHERE country = 'Bahrain (‫البحرين‬‎)' OR country = 'Bahrain (‫البحرين‬‎)' OR country = '‫البحرين‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'BD' WHERE country = 'Bangladesh (বাংলাদেশ)' OR country = 'Bangladesch (বাংলাদেশ)' OR country = 'বাংলাদেশ'");
        $this->addSql("UPDATE ShopOrder SET country = 'BB' WHERE country = 'Barbados (Barbados)' OR country = 'Barbados (Barbados)' OR country = 'Barbados'");
        $this->addSql("UPDATE ShopOrder SET country = 'BY' WHERE country = 'Belarus (Беларусь)' OR country = 'Belarus (Беларусь)' OR country = 'Беларусь'");
        $this->addSql("UPDATE ShopOrder SET country = 'BE' WHERE country = 'Belgium (België)' OR country = 'Belgien (België)' OR country = 'België'");
        $this->addSql("UPDATE ShopOrder SET country = 'BZ' WHERE country = 'Belize (Belize)' OR country = 'Belize (Belize)' OR country = 'Belize'");
        $this->addSql("UPDATE ShopOrder SET country = 'BJ' WHERE country = 'Benin (Bénin)' OR country = 'Benin (Bénin)' OR country = 'Bénin'");
        $this->addSql("UPDATE ShopOrder SET country = 'BM' WHERE country = 'Bermuda (Bermuda)' OR country = 'Bermuda (Bermuda)' OR country = 'Bermuda'");
        $this->addSql("UPDATE ShopOrder SET country = 'BT' WHERE country = 'Bhutan (འབྲུག)' OR country = 'Bhutan (འབྲུག)' OR country = 'འབྲུག'");
        $this->addSql("UPDATE ShopOrder SET country = 'BO' WHERE country = 'Bolivia (Bolivia)' OR country = 'Bolivien (Bolivia)' OR country = 'Bolivia'");
        $this->addSql("UPDATE ShopOrder SET country = 'BA' WHERE country = 'Bosnia and Herzegovina (Босна и Херцеговина)' OR country = 'Bosnien und Herzegowina (Босна и Херцеговина)' OR country = 'Босна и Херцеговина'");
        $this->addSql("UPDATE ShopOrder SET country = 'BW' WHERE country = 'Botswana (Botswana)' OR country = 'Botsuana (Botswana)' OR country = 'Botswana'");
        $this->addSql("UPDATE ShopOrder SET country = 'BV' WHERE country = 'Bouvet Island (Bouvet Island)' OR country = 'Bouvetinsel (Bouvet Island)' OR country = 'Bouvet Island'");
        $this->addSql("UPDATE ShopOrder SET country = 'BR' WHERE country = 'Brazil (Brasil)' OR country = 'Brasilien (Brasil)' OR country = 'Brasil'");
        $this->addSql("UPDATE ShopOrder SET country = 'IO' WHERE country = 'British Indian Ocean Territory (British Indian Ocean Territory)' OR country = 'Britisches Territorium im Indischen Ozean (British Indian Ocean Territory)' OR country = 'British Indian Ocean Territory'");
        $this->addSql("UPDATE ShopOrder SET country = 'VG' WHERE country = 'British Virgin Islands (British Virgin Islands)' OR country = 'Britische Jungferninseln (British Virgin Islands)' OR country = 'British Virgin Islands'");
        $this->addSql("UPDATE ShopOrder SET country = 'BN' WHERE country = 'Brunei (Brunei)' OR country = 'Brunei Darussalam (Brunei)' OR country = 'Brunei'");
        $this->addSql("UPDATE ShopOrder SET country = 'BG' WHERE country = 'Bulgaria (България)' OR country = 'Bulgarien (България)' OR country = 'България'");
        $this->addSql("UPDATE ShopOrder SET country = 'BF' WHERE country = 'Burkina Faso (Burkina Faso)' OR country = 'Burkina Faso (Burkina Faso)' OR country = 'Burkina Faso'");
        $this->addSql("UPDATE ShopOrder SET country = 'BI' WHERE country = 'Burundi (Uburundi)' OR country = 'Burundi (Uburundi)' OR country = 'Uburundi'");
        $this->addSql("UPDATE ShopOrder SET country = 'KH' WHERE country = 'Cambodia (កម្ពុជា)' OR country = 'Kambodscha (កម្ពុជា)' OR country = 'កម្ពុជា'");
        $this->addSql("UPDATE ShopOrder SET country = 'CM' WHERE country = 'Cameroon (Cameroun)' OR country = 'Kamerun (Cameroun)' OR country = 'Cameroun'");
        $this->addSql("UPDATE ShopOrder SET country = 'CA' WHERE country = 'Canada (Canada)' OR country = 'Kanada (Canada)' OR country = 'Canada'");
        $this->addSql("UPDATE ShopOrder SET country = 'IC' WHERE country = 'Canary Islands (islas Canarias)' OR country = 'Kanarische Inseln (islas Canarias)' OR country = 'islas Canarias'");
        $this->addSql("UPDATE ShopOrder SET country = 'CV' WHERE country = 'Cape Verde (Kabu Verdi)' OR country = 'Kap Verde (Kabu Verdi)' OR country = 'Kabu Verdi'");
        $this->addSql("UPDATE ShopOrder SET country = 'BQ' WHERE country = 'Caribbean Netherlands (Caribbean Netherlands)' OR country = 'Karibische Niederlande (Caribbean Netherlands)' OR country = 'Caribbean Netherlands'");
        $this->addSql("UPDATE ShopOrder SET country = 'KY' WHERE country = 'Cayman Islands (Cayman Islands)' OR country = 'Kaimaninseln (Cayman Islands)' OR country = 'Cayman Islands'");
        $this->addSql("UPDATE ShopOrder SET country = 'CF' WHERE country = 'Central African Republic (République centrafricaine)' OR country = 'Zentralafrikanische Republik (République centrafricaine)' OR country = 'République centrafricaine'");
        $this->addSql("UPDATE ShopOrder SET country = 'ES-CE' WHERE country = 'Ceuta and Melilla (Ceuta y Melilla)' OR country = 'Ceuta und Melilla (Ceuta y Melilla)' OR country = 'Ceuta y Melilla'");
        $this->addSql("UPDATE ShopOrder SET country = 'TD' WHERE country = 'Chad (Tchad)' OR country = 'Tschad (Tchad)' OR country = 'Tchad'");
        $this->addSql("UPDATE ShopOrder SET country = 'CL' WHERE country = 'Chile (Chile)' OR country = 'Chile (Chile)' OR country = 'Chile'");
        $this->addSql("UPDATE ShopOrder SET country = 'CN' WHERE country = 'China (中国)' OR country = 'China (中国)' OR country = '中国'");
        $this->addSql("UPDATE ShopOrder SET country = 'CX' WHERE country = 'Christmas Island (Christmas Island)' OR country = 'Weihnachtsinsel (Christmas Island)' OR country = 'Christmas Island'");
        $this->addSql("UPDATE ShopOrder SET country = 'CP' WHERE country = 'Clipperton Island (Clipperton Island)' OR country = 'Clipperton-Insel (Clipperton Island)' OR country = 'Clipperton Island'");
        $this->addSql("UPDATE ShopOrder SET country = 'CC' WHERE country = 'Cocos (Keeling) Islands (Kepulauan Cocos (Keeling))' OR country = 'Kokosinseln (Kepulauan Cocos (Keeling))' OR country = 'Kepulauan Cocos (Keeling)'");
        $this->addSql("UPDATE ShopOrder SET country = 'CO' WHERE country = 'Colombia (Colombia)' OR country = 'Kolumbien (Colombia)' OR country = 'Colombia'");
        $this->addSql("UPDATE ShopOrder SET country = 'KM' WHERE country = 'Comoros (‫جزر القمر‬‎)' OR country = 'Komoren (‫جزر القمر‬‎)' OR country = '‫جزر القمر‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'CD' WHERE country = 'Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)' OR country = 'Kongo-Kinshasa (Jamhuri ya Kidemokrasia ya Kongo)' OR country = 'Jamhuri ya Kidemokrasia ya Kongo'");
        $this->addSql("UPDATE ShopOrder SET country = 'CG' WHERE country = 'Congo (Republic) (Congo-Brazzaville)' OR country = 'Kongo-Brazzaville (Congo-Brazzaville)' OR country = 'Congo-Brazzaville'");
        $this->addSql("UPDATE ShopOrder SET country = 'CK' WHERE country = 'Cook Islands (Cook Islands)' OR country = 'Cookinseln (Cook Islands)' OR country = 'Cook Islands'");
        $this->addSql("UPDATE ShopOrder SET country = 'CR' WHERE country = 'Costa Rica (Costa Rica)' OR country = 'Costa Rica (Costa Rica)' OR country = 'Costa Rica'");
        $this->addSql("UPDATE ShopOrder SET country = 'CI' WHERE country = 'Côte d’Ivoire (Côte d’Ivoire)' OR country = 'Côte d’Ivoire (Côte d’Ivoire)' OR country = 'Côte d’Ivoire'");
        $this->addSql("UPDATE ShopOrder SET country = 'HR' WHERE country = 'Croatia (Hrvatska)' OR country = 'Kroatien (Hrvatska)' OR country = 'Hrvatska'");
        $this->addSql("UPDATE ShopOrder SET country = 'CU' WHERE country = 'Cuba (Cuba)' OR country = 'Kuba (Cuba)' OR country = 'Cuba'");
        $this->addSql("UPDATE ShopOrder SET country = 'CW' WHERE country = 'Curaçao (Curaçao)' OR country = 'Curaçao (Curaçao)' OR country = 'Curaçao'");
        $this->addSql("UPDATE ShopOrder SET country = 'CY' WHERE country = 'Cyprus (Κύπρος)' OR country = 'Zypern (Κύπρος)' OR country = 'Κύπρος'");
        $this->addSql("UPDATE ShopOrder SET country = 'CZ' WHERE country = 'Czech Republic (Česká republika)' OR country = 'Tschechische Republik (Česká republika)' OR country = 'Česká republika'");
        $this->addSql("UPDATE ShopOrder SET country = 'DK' WHERE country = 'Denmark (Danmark)' OR country = 'Dänemark (Danmark)' OR country = 'Danmark'");
        $this->addSql("UPDATE ShopOrder SET country = 'DG' WHERE country = 'Diego Garcia (Diego Garcia)' OR country = 'Diego Garcia (Diego Garcia)' OR country = 'Diego Garcia'");
        $this->addSql("UPDATE ShopOrder SET country = 'DJ' WHERE country = 'Djibouti (Djibouti)' OR country = 'Dschibuti (Djibouti)' OR country = 'Djibouti'");
        $this->addSql("UPDATE ShopOrder SET country = 'DM' WHERE country = 'Dominica (Dominica)' OR country = 'Dominica (Dominica)' OR country = 'Dominica'");
        $this->addSql("UPDATE ShopOrder SET country = 'DO' WHERE country = 'Dominican Republic (República Dominicana)' OR country = 'Dominikanische Republik (República Dominicana)' OR country = 'República Dominicana'");
        $this->addSql("UPDATE ShopOrder SET country = 'EC' WHERE country = 'Ecuador (Ecuador)' OR country = 'Ecuador (Ecuador)' OR country = 'Ecuador'");
        $this->addSql("UPDATE ShopOrder SET country = 'EG' WHERE country = 'Egypt (‫مصر‬‎)' OR country = 'Ägypten (‫مصر‬‎)' OR country = '‫مصر‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'SV' WHERE country = 'El Salvador (El Salvador)' OR country = 'El Salvador (El Salvador)' OR country = 'El Salvador'");
        $this->addSql("UPDATE ShopOrder SET country = 'GQ' WHERE country = 'Equatorial Guinea (Guinea Ecuatorial)' OR country = 'Äquatorialguinea (Guinea Ecuatorial)' OR country = 'Guinea Ecuatorial'");
        $this->addSql("UPDATE ShopOrder SET country = 'ER' WHERE country = 'Eritrea (Eritrea)' OR country = 'Eritrea (Eritrea)' OR country = 'Eritrea'");
        $this->addSql("UPDATE ShopOrder SET country = 'EE' WHERE country = 'Estonia (Eesti)' OR country = 'Estland (Eesti)' OR country = 'Eesti'");
        $this->addSql("UPDATE ShopOrder SET country = 'ET' WHERE country = 'Ethiopia (Ethiopia)' OR country = 'Äthiopien (Ethiopia)' OR country = 'Ethiopia'");
        $this->addSql("UPDATE ShopOrder SET country = 'FK' WHERE country = 'Falkland Islands (Islas Malvinas)' OR country = 'Falklandinseln (Islas Malvinas)' OR country = 'Islas Malvinas'");
        $this->addSql("UPDATE ShopOrder SET country = 'FO' WHERE country = 'Faroe Islands (Føroyar)' OR country = 'Färöer (Føroyar)' OR country = 'Føroyar'");
        $this->addSql("UPDATE ShopOrder SET country = 'FJ' WHERE country = 'Fiji (Fiji)' OR country = 'Fidschi (Fiji)' OR country = 'Fiji'");
        $this->addSql("UPDATE ShopOrder SET country = 'FI' WHERE country = 'Finland (Suomi)' OR country = 'Finnland (Suomi)' OR country = 'Suomi'");
        $this->addSql("UPDATE ShopOrder SET country = 'FR' WHERE country = 'France (France)' OR country = 'Frankreich (France)' OR country = 'France'");
        $this->addSql("UPDATE ShopOrder SET country = 'GF' WHERE country = 'French Guiana (Guyane française)' OR country = 'Französisch-Guayana (Guyane française)' OR country = 'Guyane française'");
        $this->addSql("UPDATE ShopOrder SET country = 'PF' WHERE country = 'French Polynesia (Polynésie française)' OR country = 'Französisch-Polynesien (Polynésie française)' OR country = 'Polynésie française'");
        $this->addSql("UPDATE ShopOrder SET country = 'TF' WHERE country = 'French Southern Territories (Terres australes françaises)' OR country = 'Französische Süd- und Antarktisgebiete (Terres australes françaises)' OR country = 'Terres australes françaises'");
        $this->addSql("UPDATE ShopOrder SET country = 'GA' WHERE country = 'Gabon (Gabon)' OR country = 'Gabun (Gabon)' OR country = 'Gabon'");
        $this->addSql("UPDATE ShopOrder SET country = 'GM' WHERE country = 'Gambia (Gambia)' OR country = 'Gambia (Gambia)' OR country = 'Gambia'");
        $this->addSql("UPDATE ShopOrder SET country = 'GE' WHERE country = 'Georgia (საქართველო)' OR country = 'Georgien (საქართველო)' OR country = 'საქართველო'");
        $this->addSql("UPDATE ShopOrder SET country = 'DE' WHERE country = 'Germany (Deutschland)' OR country = 'Deutschland (Deutschland)' OR country = 'Deutschland'");
        $this->addSql("UPDATE ShopOrder SET country = 'GH' WHERE country = 'Ghana (Gaana)' OR country = 'Ghana (Gaana)' OR country = 'Gaana'");
        $this->addSql("UPDATE ShopOrder SET country = 'GI' WHERE country = 'Gibraltar (Gibraltar)' OR country = 'Gibraltar (Gibraltar)' OR country = 'Gibraltar'");
        $this->addSql("UPDATE ShopOrder SET country = 'GR' WHERE country = 'Greece (Ελλάδα)' OR country = 'Griechenland (Ελλάδα)' OR country = 'Ελλάδα'");
        $this->addSql("UPDATE ShopOrder SET country = 'GL' WHERE country = 'Greenland (Kalaallit Nunaat)' OR country = 'Grönland (Kalaallit Nunaat)' OR country = 'Kalaallit Nunaat'");
        $this->addSql("UPDATE ShopOrder SET country = 'GD' WHERE country = 'Grenada (Grenada)' OR country = 'Grenada (Grenada)' OR country = 'Grenada'");
        $this->addSql("UPDATE ShopOrder SET country = 'GP' WHERE country = 'Guadeloupe (Guadeloupe)' OR country = 'Guadeloupe (Guadeloupe)' OR country = 'Guadeloupe'");
        $this->addSql("UPDATE ShopOrder SET country = 'GU' WHERE country = 'Guam (Guam)' OR country = 'Guam (Guam)' OR country = 'Guam'");
        $this->addSql("UPDATE ShopOrder SET country = 'GT' WHERE country = 'Guatemala (Guatemala)' OR country = 'Guatemala (Guatemala)' OR country = 'Guatemala'");
        $this->addSql("UPDATE ShopOrder SET country = 'GG' WHERE country = 'Guernsey (Guernsey)' OR country = 'Guernsey (Guernsey)' OR country = 'Guernsey'");
        $this->addSql("UPDATE ShopOrder SET country = 'GN' WHERE country = 'Guinea (Guinée)' OR country = 'Guinea (Guinée)' OR country = 'Guinée'");
        $this->addSql("UPDATE ShopOrder SET country = 'GW' WHERE country = 'Guinea-Bissau (Guiné Bissau)' OR country = 'Guinea-Bissau (Guiné Bissau)' OR country = 'Guiné Bissau'");
        $this->addSql("UPDATE ShopOrder SET country = 'GY' WHERE country = 'Guyana (Guyana)' OR country = 'Guyana (Guyana)' OR country = 'Guyana'");
        $this->addSql("UPDATE ShopOrder SET country = 'HT' WHERE country = 'Haiti (Haiti)' OR country = 'Haiti (Haiti)' OR country = 'Haiti'");
        $this->addSql("UPDATE ShopOrder SET country = 'HM' WHERE country = 'Heard & McDonald Islands (Heard & McDonald Islands)' OR country = 'Heard- und McDonald-Inseln (Heard & McDonald Islands)' OR country = 'Heard & McDonald Islands'");
        $this->addSql("UPDATE ShopOrder SET country = 'HN' WHERE country = 'Honduras (Honduras)' OR country = 'Honduras (Honduras)' OR country = 'Honduras'");
        $this->addSql("UPDATE ShopOrder SET country = 'HK' WHERE country = 'Hong Kong (香港)' OR country = 'Hongkong (香港)' OR country = '香港'");
        $this->addSql("UPDATE ShopOrder SET country = 'HU' WHERE country = 'Hungary (Magyarország)' OR country = 'Ungarn (Magyarország)' OR country = 'Magyarország'");
        $this->addSql("UPDATE ShopOrder SET country = 'IS' WHERE country = 'Iceland (Ísland)' OR country = 'Island (Ísland)' OR country = 'Ísland'");
        $this->addSql("UPDATE ShopOrder SET country = 'IN' WHERE country = 'India (भारत)' OR country = 'Indien (भारत)' OR country = 'भारत'");
        $this->addSql("UPDATE ShopOrder SET country = 'ID' WHERE country = 'Indonesia (Indonesia)' OR country = 'Indonesien (Indonesia)' OR country = 'Indonesia'");
        $this->addSql("UPDATE ShopOrder SET country = 'IR' WHERE country = 'Iran (‫ایران‬‎)' OR country = 'Iran (‫ایران‬‎)' OR country = '‫ایران‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'IQ' WHERE country = 'Iraq (‫العراق‬‎)' OR country = 'Irak (‫العراق‬‎)' OR country = '‫العراق‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'IE' WHERE country = 'Ireland (Ireland)' OR country = 'Irland (Ireland)' OR country = 'Ireland'");
        $this->addSql("UPDATE ShopOrder SET country = 'IM' WHERE country = 'Isle of Man (Isle of Man)' OR country = 'Isle of Man (Isle of Man)' OR country = 'Isle of Man'");
        $this->addSql("UPDATE ShopOrder SET country = 'IL' WHERE country = 'Israel (‫ישראל‬‎)' OR country = 'Israel (‫ישראל‬‎)' OR country = '‫ישראל‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'IT' WHERE country = 'Italy (Italia)' OR country = 'Italien (Italia)' OR country = 'Italia'");
        $this->addSql("UPDATE ShopOrder SET country = 'JM' WHERE country = 'Jamaica (Jamaica)' OR country = 'Jamaika (Jamaica)' OR country = 'Jamaica'");
        $this->addSql("UPDATE ShopOrder SET country = 'JP' WHERE country = 'Japan (日本)' OR country = 'Japan (日本)' OR country = '日本'");
        $this->addSql("UPDATE ShopOrder SET country = 'JE' WHERE country = 'Jersey (Jersey)' OR country = 'Jersey (Jersey)' OR country = 'Jersey'");
        $this->addSql("UPDATE ShopOrder SET country = 'JO' WHERE country = 'Jordan (‫الأردن‬‎)' OR country = 'Jordanien (‫الأردن‬‎)' OR country = '‫الأردن‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'KZ' WHERE country = 'Kazakhstan (Казахстан)' OR country = 'Kasachstan (Казахстан)' OR country = 'Казахстан'");
        $this->addSql("UPDATE ShopOrder SET country = 'KE' WHERE country = 'Kenya (Kenya)' OR country = 'Kenia (Kenya)' OR country = 'Kenya'");
        $this->addSql("UPDATE ShopOrder SET country = 'KI' WHERE country = 'Kiribati (Kiribati)' OR country = 'Kiribati (Kiribati)' OR country = 'Kiribati'");
        $this->addSql("UPDATE ShopOrder SET country = 'XK' WHERE country = 'Kosovo (Kosovë)' OR country = 'Kosovo (Kosovë)' OR country = 'Kosovë'");
        $this->addSql("UPDATE ShopOrder SET country = 'KW' WHERE country = 'Kuwait (‫الكويت‬‎)' OR country = 'Kuwait (‫الكويت‬‎)' OR country = '‫الكويت‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'KG' WHERE country = 'Kyrgyzstan (Кыргызстан)' OR country = 'Kirgisistan (Кыргызстан)' OR country = 'Кыргызстан'");
        $this->addSql("UPDATE ShopOrder SET country = 'LA' WHERE country = 'Laos (ລາວ)' OR country = 'Laos (ລາວ)' OR country = 'ລາວ'");
        $this->addSql("UPDATE ShopOrder SET country = 'LV' WHERE country = 'Latvia (Latvija)' OR country = 'Lettland (Latvija)' OR country = 'Latvija'");
        $this->addSql("UPDATE ShopOrder SET country = 'LB' WHERE country = 'Lebanon (‫لبنان‬‎)' OR country = 'Libanon (‫لبنان‬‎)' OR country = '‫لبنان‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'LS' WHERE country = 'Lesotho (Lesotho)' OR country = 'Lesotho (Lesotho)' OR country = 'Lesotho'");
        $this->addSql("UPDATE ShopOrder SET country = 'LR' WHERE country = 'Liberia (Liberia)' OR country = 'Liberia (Liberia)' OR country = 'Liberia'");
        $this->addSql("UPDATE ShopOrder SET country = 'LY' WHERE country = 'Libya (‫ليبيا‬‎)' OR country = 'Libyen (‫ليبيا‬‎)' OR country = '‫ليبيا‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'LI' WHERE country = 'Liechtenstein (Liechtenstein)' OR country = 'Liechtenstein (Liechtenstein)' OR country = 'Liechtenstein'");
        $this->addSql("UPDATE ShopOrder SET country = 'LT' WHERE country = 'Lithuania (Lietuva)' OR country = 'Litauen (Lietuva)' OR country = 'Lietuva'");
        $this->addSql("UPDATE ShopOrder SET country = 'LU' WHERE country = 'Luxembourg (Luxembourg)' OR country = 'Luxemburg (Luxembourg)' OR country = 'Luxembourg'");
        $this->addSql("UPDATE ShopOrder SET country = 'MO' WHERE country = 'Macau (澳門)' OR country = 'Macau (澳門)' OR country = '澳門'");
        $this->addSql("UPDATE ShopOrder SET country = 'MK' WHERE country = 'Macedonia (FYROM) (Македонија)' OR country = 'Mazedonien (Македонија)' OR country = 'Македонија'");
        $this->addSql("UPDATE ShopOrder SET country = 'MG' WHERE country = 'Madagascar (Madagasikara)' OR country = 'Madagaskar (Madagasikara)' OR country = 'Madagasikara'");
        $this->addSql("UPDATE ShopOrder SET country = 'MW' WHERE country = 'Malawi (Malawi)' OR country = 'Malawi (Malawi)' OR country = 'Malawi'");
        $this->addSql("UPDATE ShopOrder SET country = 'MY' WHERE country = 'Malaysia (Malaysia)' OR country = 'Malaysia (Malaysia)' OR country = 'Malaysia'");
        $this->addSql("UPDATE ShopOrder SET country = 'MV' WHERE country = 'Maldives (Maldives)' OR country = 'Malediven (Maldives)' OR country = 'Maldives'");
        $this->addSql("UPDATE ShopOrder SET country = 'ML' WHERE country = 'Mali (Mali)' OR country = 'Mali (Mali)' OR country = 'Mali'");
        $this->addSql("UPDATE ShopOrder SET country = 'MT' WHERE country = 'Malta (Malta)' OR country = 'Malta (Malta)' OR country = 'Malta'");
        $this->addSql("UPDATE ShopOrder SET country = 'MH' WHERE country = 'Marshall Islands (Marshall Islands)' OR country = 'Marshallinseln (Marshall Islands)' OR country = 'Marshall Islands'");
        $this->addSql("UPDATE ShopOrder SET country = 'MQ' WHERE country = 'Martinique (Martinique)' OR country = 'Martinique (Martinique)' OR country = 'Martinique'");
        $this->addSql("UPDATE ShopOrder SET country = 'MR' WHERE country = 'Mauritania (‫موريتانيا‬‎)' OR country = 'Mauretanien (‫موريتانيا‬‎)' OR country = '‫موريتانيا‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'MU' WHERE country = 'Mauritius (Moris)' OR country = 'Mauritius (Moris)' OR country = 'Moris'");
        $this->addSql("UPDATE ShopOrder SET country = 'YT' WHERE country = 'Mayotte (Mayotte)' OR country = 'Mayotte (Mayotte)' OR country = 'Mayotte'");
        $this->addSql("UPDATE ShopOrder SET country = 'MX' WHERE country = 'Mexico (México)' OR country = 'Mexiko (México)' OR country = 'México'");
        $this->addSql("UPDATE ShopOrder SET country = 'FM' WHERE country = 'Micronesia (Micronesia)' OR country = 'Mikronesien (Micronesia)' OR country = 'Micronesia'");
        $this->addSql("UPDATE ShopOrder SET country = 'MD' WHERE country = 'Moldova (Republica Moldova)' OR country = 'Republik Moldau (Republica Moldova)' OR country = 'Republica Moldova'");
        $this->addSql("UPDATE ShopOrder SET country = 'MC' WHERE country = 'Monaco (Monaco)' OR country = 'Monaco (Monaco)' OR country = 'Monaco'");
        $this->addSql("UPDATE ShopOrder SET country = 'MN' WHERE country = 'Mongolia (Монгол)' OR country = 'Mongolei (Монгол)' OR country = 'Монгол'");
        $this->addSql("UPDATE ShopOrder SET country = 'ME' WHERE country = 'Montenegro (Crna Gora)' OR country = 'Montenegro (Crna Gora)' OR country = 'Crna Gora'");
        $this->addSql("UPDATE ShopOrder SET country = 'MS' WHERE country = 'Montserrat (Montserrat)' OR country = 'Montserrat (Montserrat)' OR country = 'Montserrat'");
        $this->addSql("UPDATE ShopOrder SET country = 'MA' WHERE country = 'Morocco (‫المغرب‬‎)' OR country = 'Marokko (‫المغرب‬‎)' OR country = '‫المغرب‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'MZ' WHERE country = 'Mozambique (Moçambique)' OR country = 'Mosambik (Moçambique)' OR country = 'Moçambique'");
        $this->addSql("UPDATE ShopOrder SET country = 'MM' WHERE country = 'Myanmar (Burma) (မြန်မာ)' OR country = 'Myanmar (မြန်မာ)' OR country = 'မြန်မာ'");
        $this->addSql("UPDATE ShopOrder SET country = 'NA' WHERE country = 'Namibia (Namibië)' OR country = 'Namibia (Namibië)' OR country = 'Namibië'");
        $this->addSql("UPDATE ShopOrder SET country = 'NR' WHERE country = 'Nauru (Nauru)' OR country = 'Nauru (Nauru)' OR country = 'Nauru'");
        $this->addSql("UPDATE ShopOrder SET country = 'NP' WHERE country = 'Nepal (नेपाल)' OR country = 'Nepal (नेपाल)' OR country = 'नेपाल'");
        $this->addSql("UPDATE ShopOrder SET country = 'NL' WHERE country = 'Netherlands (Nederland)' OR country = 'Niederlande (Nederland)' OR country = 'Nederland'");
        $this->addSql("UPDATE ShopOrder SET country = 'NC' WHERE country = 'New Caledonia (Nouvelle-Calédonie)' OR country = 'Neukaledonien (Nouvelle-Calédonie)' OR country = 'Nouvelle-Calédonie'");
        $this->addSql("UPDATE ShopOrder SET country = 'NZ' WHERE country = 'New Zealand (New Zealand)' OR country = 'Neuseeland (New Zealand)' OR country = 'New Zealand'");
        $this->addSql("UPDATE ShopOrder SET country = 'NI' WHERE country = 'Nicaragua (Nicaragua)' OR country = 'Nicaragua (Nicaragua)' OR country = 'Nicaragua'");
        $this->addSql("UPDATE ShopOrder SET country = 'NE' WHERE country = 'Niger (Nijar)' OR country = 'Niger (Nijar)' OR country = 'Nijar'");
        $this->addSql("UPDATE ShopOrder SET country = 'NG' WHERE country = 'Nigeria (Nigeria)' OR country = 'Nigeria (Nigeria)' OR country = 'Nigeria'");
        $this->addSql("UPDATE ShopOrder SET country = 'NU' WHERE country = 'Niue (Niue)' OR country = 'Niue (Niue)' OR country = 'Niue'");
        $this->addSql("UPDATE ShopOrder SET country = 'NF' WHERE country = 'Norfolk Island (Norfolk Island)' OR country = 'Norfolkinsel (Norfolk Island)' OR country = 'Norfolk Island'");
        $this->addSql("UPDATE ShopOrder SET country = 'KP' WHERE country = 'North Korea (조선 민주주의 인민 공화국)' OR country = 'Demokratische Volksrepublik Korea (조선 민주주의 인민 공화국)' OR country = '조선 민주주의 인민 공화국'");
        $this->addSql("UPDATE ShopOrder SET country = 'MP' WHERE country = 'Northern Mariana Islands (Northern Mariana Islands)' OR country = 'Nördliche Marianen (Northern Mariana Islands)' OR country = 'Northern Mariana Islands'");
        $this->addSql("UPDATE ShopOrder SET country = 'NO' WHERE country = 'Norway (Norge)' OR country = 'Norwegen (Norge)' OR country = 'Norge'");
        $this->addSql("UPDATE ShopOrder SET country = 'OM' WHERE country = 'Oman (‫عُمان‬‎)' OR country = 'Oman (‫عُمان‬‎)' OR country = '‫عُمان‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'PK' WHERE country = 'Pakistan (‫پاکستان‬‎)' OR country = 'Pakistan (‫پاکستان‬‎)' OR country = '‫پاکستان‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'PW' WHERE country = 'Palau (Palau)' OR country = 'Palau (Palau)' OR country = 'Palau'");
        $this->addSql("UPDATE ShopOrder SET country = 'PS' WHERE country = 'Palestine (‫فلسطين‬‎)' OR country = 'Palästina (‫فلسطين‬‎)' OR country = '‫فلسطين‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'PA' WHERE country = 'Panama (Panamá)' OR country = 'Panama (Panamá)' OR country = 'Panamá'");
        $this->addSql("UPDATE ShopOrder SET country = 'PG' WHERE country = 'Papua New Guinea (Papua New Guinea)' OR country = 'Papua-Neuguinea (Papua New Guinea)' OR country = 'Papua New Guinea'");
        $this->addSql("UPDATE ShopOrder SET country = 'PY' WHERE country = 'Paraguay (Paraguay)' OR country = 'Paraguay (Paraguay)' OR country = 'Paraguay'");
        $this->addSql("UPDATE ShopOrder SET country = 'PE' WHERE country = 'Peru (Perú)' OR country = 'Peru (Perú)' OR country = 'Perú'");
        $this->addSql("UPDATE ShopOrder SET country = 'PH' WHERE country = 'Philippines (Philippines)' OR country = 'Philippinen (Philippines)' OR country = 'Philippines'");
        $this->addSql("UPDATE ShopOrder SET country = 'PN' WHERE country = 'Pitcairn Islands (Pitcairn Islands)' OR country = 'Pitcairninseln (Pitcairn Islands)' OR country = 'Pitcairn Islands'");
        $this->addSql("UPDATE ShopOrder SET country = 'PL' WHERE country = 'Poland (Polska)' OR country = 'Polen (Polska)' OR country = 'Polska'");
        $this->addSql("UPDATE ShopOrder SET country = 'PT' WHERE country = 'Portugal (Portugal)' OR country = 'Portugal (Portugal)' OR country = 'Portugal'");
        $this->addSql("UPDATE ShopOrder SET country = 'PR' WHERE country = 'Puerto Rico (Puerto Rico)' OR country = 'Puerto Rico (Puerto Rico)' OR country = 'Puerto Rico'");
        $this->addSql("UPDATE ShopOrder SET country = 'QA' WHERE country = 'Qatar (‫قطر‬‎)' OR country = 'Katar (‫قطر‬‎)' OR country = '‫قطر‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'RE' WHERE country = 'Réunion (La Réunion)' OR country = 'Réunion (La Réunion)' OR country = 'La Réunion'");
        $this->addSql("UPDATE ShopOrder SET country = 'RO' WHERE country = 'Romania (România)' OR country = 'Rumänien (România)' OR country = 'România'");
        $this->addSql("UPDATE ShopOrder SET country = 'RU' WHERE country = 'Russia (Россия)' OR country = 'Russische Föderation (Россия)' OR country = 'Россия'");
        $this->addSql("UPDATE ShopOrder SET country = 'RW' WHERE country = 'Rwanda (Rwanda)' OR country = 'Ruanda (Rwanda)' OR country = 'Rwanda'");
        $this->addSql("UPDATE ShopOrder SET country = 'BL' WHERE country = 'Saint Barthélemy (Saint-Barthélemy)' OR country = 'St. Barthélemy (Saint-Barthélemy)' OR country = 'Saint-Barthélemy'");
        $this->addSql("UPDATE ShopOrder SET country = 'SH-HL' WHERE country = 'Saint Helena (Saint Helena)' OR country = 'St. Helena (Saint Helena)' OR country = 'Saint Helena'");
        $this->addSql("UPDATE ShopOrder SET country = 'KN' WHERE country = 'Saint Kitts and Nevis (Saint Kitts and Nevis)' OR country = 'St. Kitts und Nevis (Saint Kitts and Nevis)' OR country = 'Saint Kitts and Nevis'");
        $this->addSql("UPDATE ShopOrder SET country = 'LC' WHERE country = 'Saint Lucia (Saint Lucia)' OR country = 'St. Lucia (Saint Lucia)' OR country = 'Saint Lucia'");
        $this->addSql("UPDATE ShopOrder SET country = 'MF' WHERE country = 'Saint Martin (Saint-Martin (partie française))' OR country = 'St. Martin (Saint-Martin (partie française))' OR country = 'Saint-Martin (partie française)'");
        $this->addSql("UPDATE ShopOrder SET country = 'PM' WHERE country = 'Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)' OR country = 'St. Pierre und Miquelon (Saint-Pierre-et-Miquelon)' OR country = 'Saint-Pierre-et-Miquelon'");
        $this->addSql("UPDATE ShopOrder SET country = 'WS' WHERE country = 'Samoa (Samoa)' OR country = 'Samoa (Samoa)' OR country = 'Samoa'");
        $this->addSql("UPDATE ShopOrder SET country = 'SM' WHERE country = 'San Marino (San Marino)' OR country = 'San Marino (San Marino)' OR country = 'San Marino'");
        $this->addSql("UPDATE ShopOrder SET country = 'ST' WHERE country = 'São Tomé and Príncipe (São Tomé e Príncipe)' OR country = 'São Tomé und Príncipe (São Tomé e Príncipe)' OR country = 'São Tomé e Príncipe'");
        $this->addSql("UPDATE ShopOrder SET country = 'SA' WHERE country = 'Saudi Arabia (‫المملكة العربية السعودية‬‎)' OR country = 'Saudi-Arabien (‫المملكة العربية السعودية‬‎)' OR country = '‫المملكة العربية السعودية‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'SN' WHERE country = 'Senegal (Sénégal)' OR country = 'Senegal (Sénégal)' OR country = 'Sénégal'");
        $this->addSql("UPDATE ShopOrder SET country = 'CS' WHERE country = 'Serbia (Србија)' OR country = 'Serbien (Србија)' OR country = 'Србија'");
        $this->addSql("UPDATE ShopOrder SET country = 'SC' WHERE country = 'Seychelles (Seychelles)' OR country = 'Seychellen (Seychelles)' OR country = 'Seychelles'");
        $this->addSql("UPDATE ShopOrder SET country = 'SL' WHERE country = 'Sierra Leone (Sierra Leone)' OR country = 'Sierra Leone (Sierra Leone)' OR country = 'Sierra Leone'");
        $this->addSql("UPDATE ShopOrder SET country = 'SG' WHERE country = 'Singapore (Singapore)' OR country = 'Singapur (Singapore)' OR country = 'Singapore'");
        $this->addSql("UPDATE ShopOrder SET country = 'SX' WHERE country = 'Sint Maarten (Sint Maarten)' OR country = 'Sint Maarten (Sint Maarten)' OR country = 'Sint Maarten'");
        $this->addSql("UPDATE ShopOrder SET country = 'SK' WHERE country = 'Slovakia (Slovensko)' OR country = 'Slowakei (Slovensko)' OR country = 'Slovensko'");
        $this->addSql("UPDATE ShopOrder SET country = 'SI' WHERE country = 'Slovenia (Slovenija)' OR country = 'Slowenien (Slovenija)' OR country = 'Slovenija'");
        $this->addSql("UPDATE ShopOrder SET country = 'SB' WHERE country = 'Solomon Islands (Solomon Islands)' OR country = 'Salomonen (Solomon Islands)' OR country = 'Solomon Islands'");
        $this->addSql("UPDATE ShopOrder SET country = 'SO' WHERE country = 'Somalia (Soomaaliya)' OR country = 'Somalia (Soomaaliya)' OR country = 'Soomaaliya'");
        $this->addSql("UPDATE ShopOrder SET country = 'ZA' WHERE country = 'South Africa (South Africa)' OR country = 'Südafrika (South Africa)' OR country = 'South Africa'");
        $this->addSql("UPDATE ShopOrder SET country = 'GS' WHERE country = 'South Georgia & South Sandwich Islands (South Georgia & South Sandwich Islands)' OR country = 'Südgeorgien und die Südlichen Sandwichinseln (South Georgia & South Sandwich Islands)' OR country = 'South Georgia & South Sandwich Islands'");
        $this->addSql("UPDATE ShopOrder SET country = 'KR' WHERE country = 'South Korea (대한민국)' OR country = 'Republik Korea (대한민국)' OR country = '대한민국'");
        $this->addSql("UPDATE ShopOrder SET country = 'SSD' WHERE country = 'South Sudan (‫جنوب السودان‬‎)' OR country = 'Südsudan (‫جنوب السودان‬‎)' OR country = '‫جنوب السودان‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'ES' WHERE country = 'Spain (España)' OR country = 'Spanien (España)' OR country = 'España'");
        $this->addSql("UPDATE ShopOrder SET country = 'LK' WHERE country = 'Sri Lanka (ශ්‍රී ලංකාව)' OR country = 'Sri Lanka (ශ්‍රී ලංකාව)' OR country = 'ශ්‍රී ලංකාව'");
        $this->addSql("UPDATE ShopOrder SET country = 'VC' WHERE country = 'St. Vincent & Grenadines (St. Vincent & Grenadines)' OR country = 'St. Vincent und die Grenadinen (St. Vincent & Grenadines)' OR country = 'St. Vincent & Grenadines'");
        $this->addSql("UPDATE ShopOrder SET country = 'SD' WHERE country = 'Sudan (‫السودان‬‎)' OR country = 'Sudan (‫السودان‬‎)' OR country = '‫السودان‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'SR' WHERE country = 'Suriname (Suriname)' OR country = 'Suriname (Suriname)' OR country = 'Suriname'");
        $this->addSql("UPDATE ShopOrder SET country = 'SJ' WHERE country = 'Svalbard and Jan Mayen (Svalbard og Jan Mayen)' OR country = 'Svalbard und Jan Mayen (Svalbard og Jan Mayen)' OR country = 'Svalbard og Jan Mayen'");
        $this->addSql("UPDATE ShopOrder SET country = 'SZ' WHERE country = 'Swaziland (Swaziland)' OR country = 'Swasiland (Swaziland)' OR country = 'Swaziland'");
        $this->addSql("UPDATE ShopOrder SET country = 'SE' WHERE country = 'Sweden (Sverige)' OR country = 'Schweden (Sverige)' OR country = 'Sverige'");
        $this->addSql("UPDATE ShopOrder SET country = 'CH' WHERE country = 'Switzerland (Schweiz)' OR country = 'Schweiz (Schweiz)' OR country = 'Schweiz'");
        $this->addSql("UPDATE ShopOrder SET country = 'SY' WHERE country = 'Syria (‫سوريا‬‎)' OR country = 'Syrien (‫سوريا‬‎)' OR country = '‫سوريا‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'TW' WHERE country = 'Taiwan (台灣)' OR country = 'Taiwan (台灣)' OR country = '台灣'");
        $this->addSql("UPDATE ShopOrder SET country = 'TJ' WHERE country = 'Tajikistan (Tajikistan)' OR country = 'Tadschikistan (Tajikistan)' OR country = 'Tajikistan'");
        $this->addSql("UPDATE ShopOrder SET country = 'TZ' WHERE country = 'Tanzania (Tanzania)' OR country = 'Tansania (Tanzania)' OR country = 'Tanzania'");
        $this->addSql("UPDATE ShopOrder SET country = 'TH' WHERE country = 'Thailand (ไทย)' OR country = 'Thailand (ไทย)' OR country = 'ไทย'");
        $this->addSql("UPDATE ShopOrder SET country = 'TL' WHERE country = 'Timor-Leste (Timor-Leste)' OR country = 'Timor-Leste (Timor-Leste)' OR country = 'Timor-Leste'");
        $this->addSql("UPDATE ShopOrder SET country = 'TG' WHERE country = 'Togo (Togo)' OR country = 'Togo (Togo)' OR country = 'Togo'");
        $this->addSql("UPDATE ShopOrder SET country = 'TK' WHERE country = 'Tokelau (Tokelau)' OR country = 'Tokelau (Tokelau)' OR country = 'Tokelau'");
        $this->addSql("UPDATE ShopOrder SET country = 'TO' WHERE country = 'Tonga (Tonga)' OR country = 'Tonga (Tonga)' OR country = 'Tonga'");
        $this->addSql("UPDATE ShopOrder SET country = 'TT' WHERE country = 'Trinidad and Tobago (Trinidad and Tobago)' OR country = 'Trinidad und Tobago (Trinidad and Tobago)' OR country = 'Trinidad and Tobago'");
        $this->addSql("UPDATE ShopOrder SET country = 'SH-TA' WHERE country = 'Tristan da Cunha (Tristan da Cunha)' OR country = 'Tristan da Cunha (Tristan da Cunha)' OR country = 'Tristan da Cunha'");
        $this->addSql("UPDATE ShopOrder SET country = 'TN' WHERE country = 'Tunisia (‫تونس‬‎)' OR country = 'Tunesien (‫تونس‬‎)' OR country = '‫تونس‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'TR' WHERE country = 'Turkey (Türkiye)' OR country = 'Türkei (Türkiye)' OR country = 'Türkiye'");
        $this->addSql("UPDATE ShopOrder SET country = 'TM' WHERE country = 'Turkmenistan (Turkmenistan)' OR country = 'Turkmenistan (Turkmenistan)' OR country = 'Turkmenistan'");
        $this->addSql("UPDATE ShopOrder SET country = 'TC' WHERE country = 'Turks and Caicos Islands (Turks and Caicos Islands)' OR country = 'Turks- und Caicosinseln (Turks and Caicos Islands)' OR country = 'Turks and Caicos Islands'");
        $this->addSql("UPDATE ShopOrder SET country = 'TV' WHERE country = 'Tuvalu (Tuvalu)' OR country = 'Tuvalu (Tuvalu)' OR country = 'Tuvalu'");
        $this->addSql("UPDATE ShopOrder SET country = 'UM' WHERE country = 'U.S. Outlying Islands (U.S. Outlying Islands)' OR country = 'Amerikanisch-Ozeanien (U.S. Outlying Islands)' OR country = 'U.S. Outlying Islands'");
        $this->addSql("UPDATE ShopOrder SET country = 'VI' WHERE country = 'U.S. Virgin Islands (U.S. Virgin Islands)' OR country = 'Amerikanische Jungferninseln (U.S. Virgin Islands)' OR country = 'U.S. Virgin Islands'");
        $this->addSql("UPDATE ShopOrder SET country = 'UG' WHERE country = 'Uganda (Uganda)' OR country = 'Uganda (Uganda)' OR country = 'Uganda'");
        $this->addSql("UPDATE ShopOrder SET country = 'UA' WHERE country = 'Ukraine (Україна)' OR country = 'Ukraine (Україна)' OR country = 'Україна'");
        $this->addSql("UPDATE ShopOrder SET country = 'AE' WHERE country = 'United Arab Emirates (‫الإمارات العربية المتحدة‬‎)' OR country = 'Vereinigte Arabische Emirate (‫الإمارات العربية المتحدة‬‎)' OR country = '‫الإمارات العربية المتحدة‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'GB' WHERE country = 'United Kingdom (United Kingdom)' OR country = 'Vereinigtes Königreich (United Kingdom)' OR country = 'United Kingdom'");
        $this->addSql("UPDATE ShopOrder SET country = 'US' WHERE country = 'United States (United States)' OR country = 'Vereinigte Staaten (United States)' OR country = 'United States'");
        $this->addSql("UPDATE ShopOrder SET country = 'UY' WHERE country = 'Uruguay (Uruguay)' OR country = 'Uruguay (Uruguay)' OR country = 'Uruguay'");
        $this->addSql("UPDATE ShopOrder SET country = 'UZ' WHERE country = 'Uzbekistan (Oʻzbekiston)' OR country = 'Usbekistan (Oʻzbekiston)' OR country = 'Oʻzbekiston'");
        $this->addSql("UPDATE ShopOrder SET country = 'VU' WHERE country = 'Vanuatu (Vanuatu)' OR country = 'Vanuatu (Vanuatu)' OR country = 'Vanuatu'");
        $this->addSql("UPDATE ShopOrder SET country = 'VA' WHERE country = 'Vatican City (Città del Vaticano)' OR country = 'Vatikanstadt (Città del Vaticano)' OR country = 'Città del Vaticano'");
        $this->addSql("UPDATE ShopOrder SET country = 'VE' WHERE country = 'Venezuela (Venezuela)' OR country = 'Venezuela (Venezuela)' OR country = 'Venezuela'");
        $this->addSql("UPDATE ShopOrder SET country = 'VN' WHERE country = 'Vietnam (Việt Nam)' OR country = 'Vietnam (Việt Nam)' OR country = 'Việt Nam'");
        $this->addSql("UPDATE ShopOrder SET country = 'WF' WHERE country = 'Wallis and Futuna (Wallis and Futuna)' OR country = 'Wallis und Futuna (Wallis and Futuna)' OR country = 'Wallis and Futuna'");
        $this->addSql("UPDATE ShopOrder SET country = 'EH' WHERE country = 'Western Sahara (‫الصحراء الغربية‬‎)' OR country = 'Westsahara (‫الصحراء الغربية‬‎)' OR country = '‫الصحراء الغربية‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'YE' WHERE country = 'Yemen (‫اليمن‬‎)' OR country = 'Jemen (‫اليمن‬‎)' OR country = '‫اليمن‬‎'");
        $this->addSql("UPDATE ShopOrder SET country = 'ZM' WHERE country = 'Zambia (Zambia)' OR country = 'Sambia (Zambia)' OR country = 'Zambia'");
        $this->addSql("UPDATE ShopOrder SET country = 'ZW' WHERE country = 'Zimbabwe (Zimbabwe)' OR country = 'Simbabwe (Zimbabwe)' OR country = 'Zimbabwe'");
    }

    public function down(Schema $schema)
    {
        $this->addSql("UPDATE ShopOrder SET country = 'Afghanistan (‫افغانستان‬‎)' WHERE country = 'AF'");
        $this->addSql("UPDATE ShopOrder SET country = 'Åland Islands (Åland)' WHERE country = 'AX'");
        $this->addSql("UPDATE ShopOrder SET country = 'Albania (Shqipëri)' WHERE country = 'AL'");
        $this->addSql("UPDATE ShopOrder SET country = 'Algeria (‫الجزائر‬‎)' WHERE country = 'DZ'");
        $this->addSql("UPDATE ShopOrder SET country = 'American Samoa (American Samoa)' WHERE country = 'AS'");
        $this->addSql("UPDATE ShopOrder SET country = 'Andorra (Andorra)' WHERE country = 'AD'");
        $this->addSql("UPDATE ShopOrder SET country = 'Angola (Angola)' WHERE country = 'AO'");
        $this->addSql("UPDATE ShopOrder SET country = 'Anguilla (Anguilla)' WHERE country = 'AI'");
        $this->addSql("UPDATE ShopOrder SET country = 'Antarctica (Antarctica)' WHERE country = 'AQ'");
        $this->addSql("UPDATE ShopOrder SET country = 'Antigua and Barbuda (Antigua and Barbuda)' WHERE country = 'AG'");
        $this->addSql("UPDATE ShopOrder SET country = 'Argentina (Argentina)' WHERE country = 'AR'");
        $this->addSql("UPDATE ShopOrder SET country = 'Armenia (Հայաստան)' WHERE country = 'AM'");
        $this->addSql("UPDATE ShopOrder SET country = 'Aruba (Aruba)' WHERE country = 'AW'");
        $this->addSql("UPDATE ShopOrder SET country = 'Ascension Island (Ascension Island)' WHERE country = 'SH-AC'");
        $this->addSql("UPDATE ShopOrder SET country = 'Australia (Australia)' WHERE country = 'AU'");
        $this->addSql("UPDATE ShopOrder SET country = 'Austria (Österreich)' WHERE country = 'AT'");
        $this->addSql("UPDATE ShopOrder SET country = 'Azerbaijan (Azərbaycan)' WHERE country = 'AZ'");
        $this->addSql("UPDATE ShopOrder SET country = 'Bahamas (Bahamas)' WHERE country = 'BS'");
        $this->addSql("UPDATE ShopOrder SET country = 'Bahrain (‫البحرين‬‎)' WHERE country = 'BH'");
        $this->addSql("UPDATE ShopOrder SET country = 'Bangladesh (বাংলাদেশ)' WHERE country = 'BD'");
        $this->addSql("UPDATE ShopOrder SET country = 'Barbados (Barbados)' WHERE country = 'BB'");
        $this->addSql("UPDATE ShopOrder SET country = 'Belarus (Беларусь)' WHERE country = 'BY'");
        $this->addSql("UPDATE ShopOrder SET country = 'Belgium (België)' WHERE country = 'BE'");
        $this->addSql("UPDATE ShopOrder SET country = 'Belize (Belize)' WHERE country = 'BZ'");
        $this->addSql("UPDATE ShopOrder SET country = 'Benin (Bénin)' WHERE country = 'BJ'");
        $this->addSql("UPDATE ShopOrder SET country = 'Bermuda (Bermuda)' WHERE country = 'BM'");
        $this->addSql("UPDATE ShopOrder SET country = 'Bhutan (འབྲུག)' WHERE country = 'BT'");
        $this->addSql("UPDATE ShopOrder SET country = 'Bolivia (Bolivia)' WHERE country = 'BO'");
        $this->addSql("UPDATE ShopOrder SET country = 'Bosnia and Herzegovina (Босна и Херцеговина)' WHERE country = 'BA'");
        $this->addSql("UPDATE ShopOrder SET country = 'Botswana (Botswana)' WHERE country = 'BW'");
        $this->addSql("UPDATE ShopOrder SET country = 'Bouvet Island (Bouvet Island)' WHERE country = 'BV'");
        $this->addSql("UPDATE ShopOrder SET country = 'Brazil (Brasil)' WHERE country = 'BR'");
        $this->addSql("UPDATE ShopOrder SET country = 'British Indian Ocean Territory (British Indian Ocean Territory)' WHERE country = 'IO'");
        $this->addSql("UPDATE ShopOrder SET country = 'British Virgin Islands (British Virgin Islands)' WHERE country = 'VG'");
        $this->addSql("UPDATE ShopOrder SET country = 'Brunei (Brunei)' WHERE country = 'BN'");
        $this->addSql("UPDATE ShopOrder SET country = 'Bulgaria (България)' WHERE country = 'BG'");
        $this->addSql("UPDATE ShopOrder SET country = 'Burkina Faso (Burkina Faso)' WHERE country = 'BF'");
        $this->addSql("UPDATE ShopOrder SET country = 'Burundi (Uburundi)' WHERE country = 'BI'");
        $this->addSql("UPDATE ShopOrder SET country = 'Cambodia (កម្ពុជា)' WHERE country = 'KH'");
        $this->addSql("UPDATE ShopOrder SET country = 'Cameroon (Cameroun)' WHERE country = 'CM'");
        $this->addSql("UPDATE ShopOrder SET country = 'Canada (Canada)' WHERE country = 'CA'");
        $this->addSql("UPDATE ShopOrder SET country = 'Canary Islands (islas Canarias)' WHERE country = 'IC'");
        $this->addSql("UPDATE ShopOrder SET country = 'Cape Verde (Kabu Verdi)' WHERE country = 'CV'");
        $this->addSql("UPDATE ShopOrder SET country = 'Caribbean Netherlands (Caribbean Netherlands)' WHERE country = 'BQ'");
        $this->addSql("UPDATE ShopOrder SET country = 'Cayman Islands (Cayman Islands)' WHERE country = 'KY'");
        $this->addSql("UPDATE ShopOrder SET country = 'Central African Republic (République centrafricaine)' WHERE country = 'CF'");
        $this->addSql("UPDATE ShopOrder SET country = 'Ceuta and Melilla (Ceuta y Melilla)' WHERE country = 'ES-CE'");
        $this->addSql("UPDATE ShopOrder SET country = 'Chad (Tchad)' WHERE country = 'TD'");
        $this->addSql("UPDATE ShopOrder SET country = 'Chile (Chile)' WHERE country = 'CL'");
        $this->addSql("UPDATE ShopOrder SET country = 'China (中国)' WHERE country = 'CN'");
        $this->addSql("UPDATE ShopOrder SET country = 'Christmas Island (Christmas Island)' WHERE country = 'CX'");
        $this->addSql("UPDATE ShopOrder SET country = 'Clipperton Island (Clipperton Island)' WHERE country = 'CP'");
        $this->addSql("UPDATE ShopOrder SET country = 'Cocos (Keeling) Islands (Kepulauan Cocos (Keeling))' WHERE country = 'CC'");
        $this->addSql("UPDATE ShopOrder SET country = 'Colombia (Colombia)' WHERE country = 'CO'");
        $this->addSql("UPDATE ShopOrder SET country = 'Comoros (‫جزر القمر‬‎)' WHERE country = 'KM'");
        $this->addSql("UPDATE ShopOrder SET country = 'Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)' WHERE country = 'CD'");
        $this->addSql("UPDATE ShopOrder SET country = 'Congo (Republic) (Congo-Brazzaville)' WHERE country = 'CG'");
        $this->addSql("UPDATE ShopOrder SET country = 'Cook Islands (Cook Islands)' WHERE country = 'CK'");
        $this->addSql("UPDATE ShopOrder SET country = 'Costa Rica (Costa Rica)' WHERE country = 'CR'");
        $this->addSql("UPDATE ShopOrder SET country = 'Côte d’Ivoire (Côte d’Ivoire)' WHERE country = 'CI'");
        $this->addSql("UPDATE ShopOrder SET country = 'Croatia (Hrvatska)' WHERE country = 'HR'");
        $this->addSql("UPDATE ShopOrder SET country = 'Cuba (Cuba)' WHERE country = 'CU'");
        $this->addSql("UPDATE ShopOrder SET country = 'Curaçao (Curaçao)' WHERE country = 'CW'");
        $this->addSql("UPDATE ShopOrder SET country = 'Cyprus (Κύπρος)' WHERE country = 'CY'");
        $this->addSql("UPDATE ShopOrder SET country = 'Czech Republic (Česká republika)' WHERE country = 'CZ'");
        $this->addSql("UPDATE ShopOrder SET country = 'Denmark (Danmark)' WHERE country = 'DK'");
        $this->addSql("UPDATE ShopOrder SET country = 'Diego Garcia (Diego Garcia)' WHERE country = 'DG'");
        $this->addSql("UPDATE ShopOrder SET country = 'Djibouti (Djibouti)' WHERE country = 'DJ'");
        $this->addSql("UPDATE ShopOrder SET country = 'Dominica (Dominica)' WHERE country = 'DM'");
        $this->addSql("UPDATE ShopOrder SET country = 'Dominican Republic (República Dominicana)' WHERE country = 'DO'");
        $this->addSql("UPDATE ShopOrder SET country = 'Ecuador (Ecuador)' WHERE country = 'EC'");
        $this->addSql("UPDATE ShopOrder SET country = 'Egypt (‫مصر‬‎)' WHERE country = 'EG'");
        $this->addSql("UPDATE ShopOrder SET country = 'El Salvador (El Salvador)' WHERE country = 'SV'");
        $this->addSql("UPDATE ShopOrder SET country = 'Equatorial Guinea (Guinea Ecuatorial)' WHERE country = 'GQ'");
        $this->addSql("UPDATE ShopOrder SET country = 'Eritrea (Eritrea)' WHERE country = 'ER'");
        $this->addSql("UPDATE ShopOrder SET country = 'Estonia (Eesti)' WHERE country = 'EE'");
        $this->addSql("UPDATE ShopOrder SET country = 'Ethiopia (Ethiopia)' WHERE country = 'ET'");
        $this->addSql("UPDATE ShopOrder SET country = 'Falkland Islands (Islas Malvinas)' WHERE country = 'FK'");
        $this->addSql("UPDATE ShopOrder SET country = 'Faroe Islands (Føroyar)' WHERE country = 'FO'");
        $this->addSql("UPDATE ShopOrder SET country = 'Fiji (Fiji)' WHERE country = 'FJ'");
        $this->addSql("UPDATE ShopOrder SET country = 'Finland (Suomi)' WHERE country = 'FI'");
        $this->addSql("UPDATE ShopOrder SET country = 'France (France)' WHERE country = 'FR'");
        $this->addSql("UPDATE ShopOrder SET country = 'French Guiana (Guyane française)' WHERE country = 'GF'");
        $this->addSql("UPDATE ShopOrder SET country = 'French Polynesia (Polynésie française)' WHERE country = 'PF'");
        $this->addSql("UPDATE ShopOrder SET country = 'French Southern Territories (Terres australes françaises)' WHERE country = 'TF'");
        $this->addSql("UPDATE ShopOrder SET country = 'Gabon (Gabon)' WHERE country = 'GA'");
        $this->addSql("UPDATE ShopOrder SET country = 'Gambia (Gambia)' WHERE country = 'GM'");
        $this->addSql("UPDATE ShopOrder SET country = 'Georgia (საქართველო)' WHERE country = 'GE'");
        $this->addSql("UPDATE ShopOrder SET country = 'Germany (Deutschland)' WHERE country = 'DE'");
        $this->addSql("UPDATE ShopOrder SET country = 'Ghana (Gaana)' WHERE country = 'GH'");
        $this->addSql("UPDATE ShopOrder SET country = 'Gibraltar (Gibraltar)' WHERE country = 'GI'");
        $this->addSql("UPDATE ShopOrder SET country = 'Greece (Ελλάδα)' WHERE country = 'GR'");
        $this->addSql("UPDATE ShopOrder SET country = 'Greenland (Kalaallit Nunaat)' WHERE country = 'GL'");
        $this->addSql("UPDATE ShopOrder SET country = 'Grenada (Grenada)' WHERE country = 'GD'");
        $this->addSql("UPDATE ShopOrder SET country = 'Guadeloupe (Guadeloupe)' WHERE country = 'GP'");
        $this->addSql("UPDATE ShopOrder SET country = 'Guam (Guam)' WHERE country = 'GU'");
        $this->addSql("UPDATE ShopOrder SET country = 'Guatemala (Guatemala)' WHERE country = 'GT'");
        $this->addSql("UPDATE ShopOrder SET country = 'Guernsey (Guernsey)' WHERE country = 'GG'");
        $this->addSql("UPDATE ShopOrder SET country = 'Guinea (Guinée)' WHERE country = 'GN'");
        $this->addSql("UPDATE ShopOrder SET country = 'Guinea-Bissau (Guiné Bissau)' WHERE country = 'GW'");
        $this->addSql("UPDATE ShopOrder SET country = 'Guyana (Guyana)' WHERE country = 'GY'");
        $this->addSql("UPDATE ShopOrder SET country = 'Haiti (Haiti)' WHERE country = 'HT'");
        $this->addSql("UPDATE ShopOrder SET country = 'Heard & McDonald Islands (Heard & McDonald Islands)' WHERE country = 'HM'");
        $this->addSql("UPDATE ShopOrder SET country = 'Honduras (Honduras)' WHERE country = 'HN'");
        $this->addSql("UPDATE ShopOrder SET country = 'Hong Kong (香港)' WHERE country = 'HK'");
        $this->addSql("UPDATE ShopOrder SET country = 'Hungary (Magyarország)' WHERE country = 'HU'");
        $this->addSql("UPDATE ShopOrder SET country = 'Iceland (Ísland)' WHERE country = 'IS'");
        $this->addSql("UPDATE ShopOrder SET country = 'India (भारत)' WHERE country = 'IN'");
        $this->addSql("UPDATE ShopOrder SET country = 'Indonesia (Indonesia)' WHERE country = 'ID'");
        $this->addSql("UPDATE ShopOrder SET country = 'Iran (‫ایران‬‎)' WHERE country = 'IR'");
        $this->addSql("UPDATE ShopOrder SET country = 'Iraq (‫العراق‬‎)' WHERE country = 'IQ'");
        $this->addSql("UPDATE ShopOrder SET country = 'Ireland (Ireland)' WHERE country = 'IE'");
        $this->addSql("UPDATE ShopOrder SET country = 'Isle of Man (Isle of Man)' WHERE country = 'IM'");
        $this->addSql("UPDATE ShopOrder SET country = 'Israel (‫ישראל‬‎)' WHERE country = 'IL'");
        $this->addSql("UPDATE ShopOrder SET country = 'Italy (Italia)' WHERE country = 'IT'");
        $this->addSql("UPDATE ShopOrder SET country = 'Jamaica (Jamaica)' WHERE country = 'JM'");
        $this->addSql("UPDATE ShopOrder SET country = 'Japan (日本)' WHERE country = 'JP'");
        $this->addSql("UPDATE ShopOrder SET country = 'Jersey (Jersey)' WHERE country = 'JE'");
        $this->addSql("UPDATE ShopOrder SET country = 'Jordan (‫الأردن‬‎)' WHERE country = 'JO'");
        $this->addSql("UPDATE ShopOrder SET country = 'Kazakhstan (Казахстан)' WHERE country = 'KZ'");
        $this->addSql("UPDATE ShopOrder SET country = 'Kenya (Kenya)' WHERE country = 'KE'");
        $this->addSql("UPDATE ShopOrder SET country = 'Kiribati (Kiribati)' WHERE country = 'KI'");
        $this->addSql("UPDATE ShopOrder SET country = 'Kosovo (Kosovë)' WHERE country = 'XK'");
        $this->addSql("UPDATE ShopOrder SET country = 'Kuwait (‫الكويت‬‎)' WHERE country = 'KW'");
        $this->addSql("UPDATE ShopOrder SET country = 'Kyrgyzstan (Кыргызстан)' WHERE country = 'KG'");
        $this->addSql("UPDATE ShopOrder SET country = 'Laos (ລາວ)' WHERE country = 'LA'");
        $this->addSql("UPDATE ShopOrder SET country = 'Latvia (Latvija)' WHERE country = 'LV'");
        $this->addSql("UPDATE ShopOrder SET country = 'Lebanon (‫لبنان‬‎)' WHERE country = 'LB'");
        $this->addSql("UPDATE ShopOrder SET country = 'Lesotho (Lesotho)' WHERE country = 'LS'");
        $this->addSql("UPDATE ShopOrder SET country = 'Liberia (Liberia)' WHERE country = 'LR'");
        $this->addSql("UPDATE ShopOrder SET country = 'Libya (‫ليبيا‬‎)' WHERE country = 'LY'");
        $this->addSql("UPDATE ShopOrder SET country = 'Liechtenstein (Liechtenstein)' WHERE country = 'LI'");
        $this->addSql("UPDATE ShopOrder SET country = 'Lithuania (Lietuva)' WHERE country = 'LT'");
        $this->addSql("UPDATE ShopOrder SET country = 'Luxembourg (Luxembourg)' WHERE country = 'LU'");
        $this->addSql("UPDATE ShopOrder SET country = 'Macau (澳門)' WHERE country = 'MO'");
        $this->addSql("UPDATE ShopOrder SET country = 'Macedonia (FYROM) (Македонија)' WHERE country = 'MK'");
        $this->addSql("UPDATE ShopOrder SET country = 'Madagascar (Madagasikara)' WHERE country = 'MG'");
        $this->addSql("UPDATE ShopOrder SET country = 'Malawi (Malawi)' WHERE country = 'MW'");
        $this->addSql("UPDATE ShopOrder SET country = 'Malaysia (Malaysia)' WHERE country = 'MY'");
        $this->addSql("UPDATE ShopOrder SET country = 'Maldives (Maldives)' WHERE country = 'MV'");
        $this->addSql("UPDATE ShopOrder SET country = 'Mali (Mali)' WHERE country = 'ML'");
        $this->addSql("UPDATE ShopOrder SET country = 'Malta (Malta)' WHERE country = 'MT'");
        $this->addSql("UPDATE ShopOrder SET country = 'Marshall Islands (Marshall Islands)' WHERE country = 'MH'");
        $this->addSql("UPDATE ShopOrder SET country = 'Martinique (Martinique)' WHERE country = 'MQ'");
        $this->addSql("UPDATE ShopOrder SET country = 'Mauritania (‫موريتانيا‬‎)' WHERE country = 'MR'");
        $this->addSql("UPDATE ShopOrder SET country = 'Mauritius (Moris)' WHERE country = 'MU'");
        $this->addSql("UPDATE ShopOrder SET country = 'Mayotte (Mayotte)' WHERE country = 'YT'");
        $this->addSql("UPDATE ShopOrder SET country = 'Mexico (México)' WHERE country = 'MX'");
        $this->addSql("UPDATE ShopOrder SET country = 'Micronesia (Micronesia)' WHERE country = 'FM'");
        $this->addSql("UPDATE ShopOrder SET country = 'Moldova (Republica Moldova)' WHERE country = 'MD'");
        $this->addSql("UPDATE ShopOrder SET country = 'Monaco (Monaco)' WHERE country = 'MC'");
        $this->addSql("UPDATE ShopOrder SET country = 'Mongolia (Монгол)' WHERE country = 'MN'");
        $this->addSql("UPDATE ShopOrder SET country = 'Montenegro (Crna Gora)' WHERE country = 'ME'");
        $this->addSql("UPDATE ShopOrder SET country = 'Montserrat (Montserrat)' WHERE country = 'MS'");
        $this->addSql("UPDATE ShopOrder SET country = 'Morocco (‫المغرب‬‎)' WHERE country = 'MA'");
        $this->addSql("UPDATE ShopOrder SET country = 'Mozambique (Moçambique)' WHERE country = 'MZ'");
        $this->addSql("UPDATE ShopOrder SET country = 'Myanmar (Burma) (မြန်မာ)' WHERE country = 'MM'");
        $this->addSql("UPDATE ShopOrder SET country = 'Namibia (Namibië)' WHERE country = 'NA'");
        $this->addSql("UPDATE ShopOrder SET country = 'Nauru (Nauru)' WHERE country = 'NR'");
        $this->addSql("UPDATE ShopOrder SET country = 'Nepal (नेपाल)' WHERE country = 'NP'");
        $this->addSql("UPDATE ShopOrder SET country = 'Netherlands (Nederland)' WHERE country = 'NL'");
        $this->addSql("UPDATE ShopOrder SET country = 'New Caledonia (Nouvelle-Calédonie)' WHERE country = 'NC'");
        $this->addSql("UPDATE ShopOrder SET country = 'New Zealand (New Zealand)' WHERE country = 'NZ'");
        $this->addSql("UPDATE ShopOrder SET country = 'Nicaragua (Nicaragua)' WHERE country = 'NI'");
        $this->addSql("UPDATE ShopOrder SET country = 'Niger (Nijar)' WHERE country = 'NE'");
        $this->addSql("UPDATE ShopOrder SET country = 'Nigeria (Nigeria)' WHERE country = 'NG'");
        $this->addSql("UPDATE ShopOrder SET country = 'Niue (Niue)' WHERE country = 'NU'");
        $this->addSql("UPDATE ShopOrder SET country = 'Norfolk Island (Norfolk Island)' WHERE country = 'NF'");
        $this->addSql("UPDATE ShopOrder SET country = 'North Korea (조선 민주주의 인민 공화국)' WHERE country = 'KP'");
        $this->addSql("UPDATE ShopOrder SET country = 'Northern Mariana Islands (Northern Mariana Islands)' WHERE country = 'MP'");
        $this->addSql("UPDATE ShopOrder SET country = 'Norway (Norge)' WHERE country = 'NO'");
        $this->addSql("UPDATE ShopOrder SET country = 'Oman (‫عُمان‬‎)' WHERE country = 'OM'");
        $this->addSql("UPDATE ShopOrder SET country = 'Pakistan (‫پاکستان‬‎)' WHERE country = 'PK'");
        $this->addSql("UPDATE ShopOrder SET country = 'Palau (Palau)' WHERE country = 'PW'");
        $this->addSql("UPDATE ShopOrder SET country = 'Palestine (‫فلسطين‬‎)' WHERE country = 'PS'");
        $this->addSql("UPDATE ShopOrder SET country = 'Panama (Panamá)' WHERE country = 'PA'");
        $this->addSql("UPDATE ShopOrder SET country = 'Papua New Guinea (Papua New Guinea)' WHERE country = 'PG'");
        $this->addSql("UPDATE ShopOrder SET country = 'Paraguay (Paraguay)' WHERE country = 'PY'");
        $this->addSql("UPDATE ShopOrder SET country = 'Peru (Perú)' WHERE country = 'PE'");
        $this->addSql("UPDATE ShopOrder SET country = 'Philippines (Philippines)' WHERE country = 'PH'");
        $this->addSql("UPDATE ShopOrder SET country = 'Pitcairn Islands (Pitcairn Islands)' WHERE country = 'PN'");
        $this->addSql("UPDATE ShopOrder SET country = 'Poland (Polska)' WHERE country = 'PL'");
        $this->addSql("UPDATE ShopOrder SET country = 'Portugal (Portugal)' WHERE country = 'PT'");
        $this->addSql("UPDATE ShopOrder SET country = 'Puerto Rico (Puerto Rico)' WHERE country = 'PR'");
        $this->addSql("UPDATE ShopOrder SET country = 'Qatar (‫قطر‬‎)' WHERE country = 'QA'");
        $this->addSql("UPDATE ShopOrder SET country = 'Réunion (La Réunion)' WHERE country = 'RE'");
        $this->addSql("UPDATE ShopOrder SET country = 'Romania (România)' WHERE country = 'RO'");
        $this->addSql("UPDATE ShopOrder SET country = 'Russia (Россия)' WHERE country = 'RU'");
        $this->addSql("UPDATE ShopOrder SET country = 'Rwanda (Rwanda)' WHERE country = 'RW'");
        $this->addSql("UPDATE ShopOrder SET country = 'Saint Barthélemy (Saint-Barthélemy)' WHERE country = 'BL'");
        $this->addSql("UPDATE ShopOrder SET country = 'Saint Helena (Saint Helena)' WHERE country = 'SH-HL'");
        $this->addSql("UPDATE ShopOrder SET country = 'Saint Kitts and Nevis (Saint Kitts and Nevis)' WHERE country = 'KN'");
        $this->addSql("UPDATE ShopOrder SET country = 'Saint Lucia (Saint Lucia)' WHERE country = 'LC'");
        $this->addSql("UPDATE ShopOrder SET country = 'Saint Martin (Saint-Martin (partie française))' WHERE country = 'MF'");
        $this->addSql("UPDATE ShopOrder SET country = 'Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)' WHERE country = 'PM'");
        $this->addSql("UPDATE ShopOrder SET country = 'Samoa (Samoa)' WHERE country = 'WS'");
        $this->addSql("UPDATE ShopOrder SET country = 'San Marino (San Marino)' WHERE country = 'SM'");
        $this->addSql("UPDATE ShopOrder SET country = 'São Tomé and Príncipe (São Tomé e Príncipe)' WHERE country = 'ST'");
        $this->addSql("UPDATE ShopOrder SET country = 'Saudi Arabia (‫المملكة العربية السعودية‬‎)' WHERE country = 'SA'");
        $this->addSql("UPDATE ShopOrder SET country = 'Senegal (Sénégal)' WHERE country = 'SN'");
        $this->addSql("UPDATE ShopOrder SET country = 'Serbia (Србија)' WHERE country = 'CS'");
        $this->addSql("UPDATE ShopOrder SET country = 'Seychelles (Seychelles)' WHERE country = 'SC'");
        $this->addSql("UPDATE ShopOrder SET country = 'Sierra Leone (Sierra Leone)' WHERE country = 'SL'");
        $this->addSql("UPDATE ShopOrder SET country = 'Singapore (Singapore)' WHERE country = 'SG'");
        $this->addSql("UPDATE ShopOrder SET country = 'Sint Maarten (Sint Maarten)' WHERE country = 'SX'");
        $this->addSql("UPDATE ShopOrder SET country = 'Slovakia (Slovensko)' WHERE country = 'SK'");
        $this->addSql("UPDATE ShopOrder SET country = 'Slovenia (Slovenija)' WHERE country = 'SI'");
        $this->addSql("UPDATE ShopOrder SET country = 'Solomon Islands (Solomon Islands)' WHERE country = 'SB'");
        $this->addSql("UPDATE ShopOrder SET country = 'Somalia (Soomaaliya)' WHERE country = 'SO'");
        $this->addSql("UPDATE ShopOrder SET country = 'South Africa (South Africa)' WHERE country = 'ZA'");
        $this->addSql("UPDATE ShopOrder SET country = 'South Georgia & South Sandwich Islands (South Georgia & South Sandwich Islands)' WHERE country = 'GS'");
        $this->addSql("UPDATE ShopOrder SET country = 'South Korea (대한민국)' WHERE country = 'KR'");
        $this->addSql("UPDATE ShopOrder SET country = 'South Sudan (‫جنوب السودان‬‎)' WHERE country = 'SSD'");
        $this->addSql("UPDATE ShopOrder SET country = 'Spain (España)' WHERE country = 'ES'");
        $this->addSql("UPDATE ShopOrder SET country = 'Sri Lanka (ශ්‍රී ලංකාව)' WHERE country = 'LK'");
        $this->addSql("UPDATE ShopOrder SET country = 'St. Vincent & Grenadines (St. Vincent & Grenadines)' WHERE country = 'VC'");
        $this->addSql("UPDATE ShopOrder SET country = 'Sudan (‫السودان‬‎)' WHERE country = 'SD'");
        $this->addSql("UPDATE ShopOrder SET country = 'Suriname (Suriname)' WHERE country = 'SR'");
        $this->addSql("UPDATE ShopOrder SET country = 'Svalbard and Jan Mayen (Svalbard og Jan Mayen)' WHERE country = 'SJ'");
        $this->addSql("UPDATE ShopOrder SET country = 'Swaziland (Swaziland)' WHERE country = 'SZ'");
        $this->addSql("UPDATE ShopOrder SET country = 'Sweden (Sverige)' WHERE country = 'SE'");
        $this->addSql("UPDATE ShopOrder SET country = 'Switzerland (Schweiz)' WHERE country = 'CH'");
        $this->addSql("UPDATE ShopOrder SET country = 'Syria (‫سوريا‬‎)' WHERE country = 'SY'");
        $this->addSql("UPDATE ShopOrder SET country = 'Taiwan (台灣)' WHERE country = 'TW'");
        $this->addSql("UPDATE ShopOrder SET country = 'Tajikistan (Tajikistan)' WHERE country = 'TJ'");
        $this->addSql("UPDATE ShopOrder SET country = 'Tanzania (Tanzania)' WHERE country = 'TZ'");
        $this->addSql("UPDATE ShopOrder SET country = 'Thailand (ไทย)' WHERE country = 'TH'");
        $this->addSql("UPDATE ShopOrder SET country = 'Timor-Leste (Timor-Leste)' WHERE country = 'TL'");
        $this->addSql("UPDATE ShopOrder SET country = 'Togo (Togo)' WHERE country = 'TG'");
        $this->addSql("UPDATE ShopOrder SET country = 'Tokelau (Tokelau)' WHERE country = 'TK'");
        $this->addSql("UPDATE ShopOrder SET country = 'Tonga (Tonga)' WHERE country = 'TO'");
        $this->addSql("UPDATE ShopOrder SET country = 'Trinidad and Tobago (Trinidad and Tobago)' WHERE country = 'TT'");
        $this->addSql("UPDATE ShopOrder SET country = 'Tristan da Cunha (Tristan da Cunha)' WHERE country = 'SH-TA'");
        $this->addSql("UPDATE ShopOrder SET country = 'Tunisia (‫تونس‬‎)' WHERE country = 'TN'");
        $this->addSql("UPDATE ShopOrder SET country = 'Turkey (Türkiye)' WHERE country = 'TR'");
        $this->addSql("UPDATE ShopOrder SET country = 'Turkmenistan (Turkmenistan)' WHERE country = 'TM'");
        $this->addSql("UPDATE ShopOrder SET country = 'Turks and Caicos Islands (Turks and Caicos Islands)' WHERE country = 'TC'");
        $this->addSql("UPDATE ShopOrder SET country = 'Tuvalu (Tuvalu)' WHERE country = 'TV'");
        $this->addSql("UPDATE ShopOrder SET country = 'U.S. Outlying Islands (U.S. Outlying Islands)' WHERE country = 'UM'");
        $this->addSql("UPDATE ShopOrder SET country = 'U.S. Virgin Islands (U.S. Virgin Islands)' WHERE country = 'VI'");
        $this->addSql("UPDATE ShopOrder SET country = 'Uganda (Uganda)' WHERE country = 'UG'");
        $this->addSql("UPDATE ShopOrder SET country = 'Ukraine (Україна)' WHERE country = 'UA'");
        $this->addSql("UPDATE ShopOrder SET country = 'United Arab Emirates (‫الإمارات العربية المتحدة‬‎)' WHERE country = 'AE'");
        $this->addSql("UPDATE ShopOrder SET country = 'United Kingdom (United Kingdom)' WHERE country = 'GB'");
        $this->addSql("UPDATE ShopOrder SET country = 'United States (United States)' WHERE country = 'US'");
        $this->addSql("UPDATE ShopOrder SET country = 'Uruguay (Uruguay)' WHERE country = 'UY'");
        $this->addSql("UPDATE ShopOrder SET country = 'Uzbekistan (Oʻzbekiston)' WHERE country = 'UZ'");
        $this->addSql("UPDATE ShopOrder SET country = 'Vanuatu (Vanuatu)' WHERE country = 'VU'");
        $this->addSql("UPDATE ShopOrder SET country = 'Vatican City (Città del Vaticano)' WHERE country = 'VA'");
        $this->addSql("UPDATE ShopOrder SET country = 'Venezuela (Venezuela)' WHERE country = 'VE'");
        $this->addSql("UPDATE ShopOrder SET country = 'Vietnam (Việt Nam)' WHERE country = 'VN'");
        $this->addSql("UPDATE ShopOrder SET country = 'Wallis and Futuna (Wallis and Futuna)' WHERE country = 'WF'");
        $this->addSql("UPDATE ShopOrder SET country = 'Western Sahara (‫الصحراء الغربية‬‎)' WHERE country = 'EH'");
        $this->addSql("UPDATE ShopOrder SET country = 'Yemen (‫اليمن‬‎)' WHERE country = 'YE'");
        $this->addSql("UPDATE ShopOrder SET country = 'Zambia (Zambia)' WHERE country = 'ZM'");
        $this->addSql("UPDATE ShopOrder SET country = 'Zimbabwe (Zimbabwe)' WHERE country = 'ZW'");
    }
}
