dothiv_premiumconfig_page:
    host: %charitydomain%
    schemes:  [https]
    path:     /{locale}/premium-configurator/{domain}
    defaults:
        _controller: dothiv.premiumconfigurator.controller.page:configuratorPageAction
    requirements:
        locale: ^(en|de|ky)$

dothiv_premiumconfig_preview:
    host: %charitydomain%
    schemes:  [https]
    path:     /{locale}/premium-configurator/{domain}/preview
    defaults:
        _controller: dothiv.premiumconfigurator.controller.preview:previewAction
    requirements:
        locale: ^(en|de|ky)$

dothiv_premiumconfig_blank:
    host: %charitydomain%
    schemes:  [https]
    path:     /{locale}/premium-configurator/{domain}/blank
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'DothivPremiumConfiguratorBundle:Page:blank.html.twig'
    requirements:
        locale: ^(en|de|ky)$

dothiv_premiumconfig_preview_config:
    host: %charitydomain%
    schemes:  [https]
    path:     /{locale}/premium-configurator/{domain}/config.json
    defaults:
        _controller: dothiv.premiumconfigurator.controller.preview:previewBannerConfigAction
    requirements:
        locale: ^(en|de|ky)$

dothiv_premiumconfig_preview_banner:
    host: %charitydomain%
    schemes:  [https]
    path:     /{locale}/premium-configurator/{domain}/{file}
    defaults:
        _controller: dothiv.premiumconfigurator.controller.preview:previewBannerFileAction
    requirements:
        file: ^clickcounter-(top|bottom|left|right|topleft-micro|top-micro|topright-micro).html
    requirements:
        locale: ^(en|de|ky)$

dothiv_premiumconfig_page_app:
    host: %charitydomain%
    schemes:  [https]
    path:     /{locale}/premium-configurator/{domain}/app/{page}.html
    defaults:
        _controller: dothiv.premiumconfigurator.controller.page:configuratorAppPageAction
    requirements:
        locale: ^(en|de|ky)$

dothiv_premiumconfig_attachment:
    host: %charitydomain%
    schemes:  [https]
    path:     /api/premium-configurator/image
    defaults:
        _controller: dothiv.premiumconfigurator.api.controller.attachment:createAction
        _format: json
    methods: [POST]

dothiv_premiumconfig_banner_config_set:
    host: %charitydomain%
    schemes:  [https]
    path:     /api/premium-configurator/{name}/banner
    defaults:
        _controller: dothiv.premiumconfigurator.api.controller.banner:setConfigAction
        _format: json
    methods: [PUT]

dothiv_premiumconfig_banner_config_get:
    host: %charitydomain%
    schemes:  [https]
    path:     /api/premium-configurator/{name}/banner
    defaults:
        _controller: dothiv.premiumconfigurator.api.controller.banner:getConfigAction
        _format: json
    methods: [GET]

dothiv_premiumconfig_banner_subscription_set:
    host: %charitydomain%
    schemes:  [https]
    path:     /api/premium-configurator/{name}/subscription
    defaults:
        _controller: dothiv.premiumconfigurator.api.controller.subscription:setSubscriptionAction
        _format: json
    methods: [PUT]

dothiv_premiumconfig_banner_subscription_get:
    host: %charitydomain%
    schemes:  [https]
    path:     /api/premium-configurator/{name}/subscription
    defaults:
        _controller: dothiv.premiumconfigurator.api.controller.subscription:getSubscriptionAction
        _format: json
    methods: [GET]

## Premium Click-Counter Preview for non-ssl sites
dothiv_premiumconfig_preview_non_ssl:
    host: %clickCounterPreviewDomainNonSSL%
    schemes:  [http]
    path:     /{domain}/preview
    defaults:
        locale: en
        _controller: dothiv.premiumconfigurator.controller.preview:previewAction

dothiv_premiumconfig_preview_config_non_ssl:
    host: %clickCounterPreviewDomainNonSSL%
    schemes:  [http]
    path:     /{domain}/config.json
    defaults:
        _controller: dothiv.premiumconfigurator.controller.preview:previewBannerConfigAction
        locale: en

dothiv_premiumconfig_preview_banner_non_ssl:
    host: %clickCounterPreviewDomainNonSSL%
    schemes:  [http]
    path:     /{domain}/{file}
    defaults:
        _controller: dothiv.premiumconfigurator.controller.preview:previewBannerFileAction
        locale: en
    requirements:
        file: ^clickcounter-(top|bottom|left|right|topleft-micro|top-micro|topright-micro).html
