parameters:
    dothiv.premiumconfigurator.service.attachment_store.class: Dothiv\PremiumConfiguratorBundle\Service\AttachmentStoreService
    dothiv.premiumconfigurator.service.invoice.class: Dothiv\PremiumConfiguratorBundle\Service\InvoiceService
    dothiv.premiumconfigurator.mailer.subscription_confirmed.class: Dothiv\PremiumConfiguratorBundle\Service\Mailer\SubscriptionConfirmedMailer
    dothiv.premiumconfigurator.configuration_decorator.class: Dothiv\PremiumConfiguratorBundle\Service\PremiumClickCounterConfigurationDecorator

services:
    dothiv.premiumconfigurator.service.attachment:
        class: %dothiv.businessbundle.service.attachment.class%
        arguments:
        - @dothiv.repository.attachment
        - ['image/png', 'image/jpeg', 'image/gif']
        - @dothiv.premiumconfigurator.service.attachment_store

    dothiv.premiumconfigurator.service.attachment_store:
        class: %dothiv.premiumconfigurator.service.attachment_store.class%
        arguments:
        - %dothiv_premium_configurator.attachments%
        - @dothiv.websitebase.service.image_scaler
        - %charitydomain%

    dothiv.premiumconfigurator.service.invoice:
        class: %dothiv.premiumconfigurator.service.invoice.class%
        arguments:
        - @dothiv.repository.invoice
        - %premium_price%
        - @dothiv.business.service.vatrules

    dothiv.premiumconfigurator.mailer.subscription_confirmed:
        class: %dothiv.premiumconfigurator.mailer.subscription_confirmed.class%
        arguments:
        - @dothiv.charity.service.mailer.content
        - @dothiv.websitebase.money_format
        - @dothiv.business.service.vatrules

    dothiv.premiumconfigurator.configuration_decorator:
        class: %dothiv.premiumconfigurator.configuration_decorator.class%
        arguments:
        - @dothiv.premiumconfigurator.service.attachment_store
