services:
    dothiv.shop.controller.page:
        class: Dothiv\BaseWebsiteBundle\Controller\PageController
        arguments:
          - @dothiv.websitebase.cache.request_lastmodified
          - @templating
          - @dothiv.registry.contentful.registry_content
          - "DothivShopBundle"
          - @clock
          - %page_lifetime%
