services:
    dothiv.shop.controller.page:
        class: Dothiv\BaseWebsiteBundle\Controller\PageController
        arguments:
          - @dothiv.websitebase.cache.request_lastmodified
          - @templating
          - @dothiv.registry.contentful.registry_content
          - "DothivShopBundle"
          - @clock
          - %page_lifetime%


    dothiv.shop.controller.api:
        class: Dothiv\ShopBundle\Controller\ApiController
        arguments:
        - @dothiv.repository.domain_info
        - @dothiv.repository.config
        - @dothiv.shop.transformer.domain_info
        - @serializer
