services:
    dothiv.shop.controller.page:
        class: Dothiv\BaseWebsiteBundle\Controller\PageController
        arguments:
          - @dothiv.websitebase.cache.request_lastmodified
          - @templating
          - @dothiv.registry.contentful.registry_content
          - "DothivShopBundle"
          - @clock
          - %page_lifetime%

    dothiv.shop.controller.api.lookup:
        class: Dothiv\ShopBundle\Controller\ApiController
        arguments:
        - @dothiv.repository.domain_info
        - @dothiv.repository.config
        - @dothiv.shop.transformer.domain_info
        - @serializer

    dothiv.shop.controller.api.order:
        class: Dothiv\ShopBundle\Controller\OrderController
        arguments:
        - @dothiv.repository.domain_info
        - @dothiv.repository.shop_order
        - @dothiv.shop.manipulator.order
        - @dothiv.business.event_dispatcher
