parameters:
    dothiv.shop.listener.http_exception.class: Dothiv\ShopBundle\Listener\HttpExceptionListener

services:
    dothiv.shop.listener.http_exception:
        class: %dothiv.shop.listener.http_exception.class%
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
