parameters:
    dothiv.repository.domain_info.entity: 'DothivShopBundle:DomainInfo'
    dothiv.repository.domain_info.repository.class: Dothiv\ShopBundle\Repository\DomainInfoRepository

services:
    dothiv.repository.domain_info:
        class: %dothiv.repository.domain_info.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ %dothiv.repository.domain_info.entity% ]
        calls:
        - [setValidator, ["@validator"]]
