parameters:
    dothiv.shop.transformer.domain_info.class: Dothiv\ShopBundle\Transformer\DomainInfoTransformer
    dothiv.shop.manipulator.order.class: Dothiv\ShopBundle\Manipulator\OrderManipulator

services:
    dothiv.shop.transformer.domain_info:
        class: %dothiv.shop.transformer.domain_info.class%
        arguments:
        - @router
        - "dothiv_shop_api_info"

    dothiv.shop.manipulator.order:
        class: %dothiv.shop.manipulator.order.class%
