parameters:
    dothiv.shop.transformer.domain_info.class: Dothiv\ShopBundle\Transformer\DomainInfoTransformer
    dothiv.shop.manipulator.order.class: Dothiv\ShopBundle\Manipulator\OrderManipulator
    dothiv.shop.domain_price.class: Dothiv\ShopBundle\Service\DomainPriceService
    dothiv.shop.invoice.class: Dothiv\ShopBundle\Service\InvoiceService
    dothiv.shop.mailer.order.class: Dothiv\ShopBundle\Service\OrderMailer
    dothiv.shop.genitivfy.class: Dothiv\ShopBundle\Service\GenitivfyService

services:
    dothiv.shop.transformer.domain_info:
        class: %dothiv.shop.transformer.domain_info.class%
        arguments:
        - @router
        - "dothiv_shop_api_info"

    dothiv.shop.manipulator.order:
        class: %dothiv.shop.manipulator.order.class%

    dothiv.shop.domain_price:
        class: %dothiv.shop.domain_price.class%
        arguments:
        - @dothiv.repository.config

    dothiv.shop.invoice:
        class: %dothiv.shop.invoice.class%
        arguments:
        - @dothiv.repository.invoice
        - @dothiv.shop.domain_price
        - @dothiv.business.service.vatrules

    dothiv.shop.mailer.order:
        class: %dothiv.shop.mailer.order.class%
        arguments:
        - @dothiv.registry.service.mailer.content
        - @dothiv.websitebase.money_format
        - @dothiv.business.service.vatrules

    dothiv.shop.name4life_landingpage_content:
        class: %dothiv.websitebase.contentful.content.class%
        arguments:
            - @dothiv_contentful.content
            - @dothiv.websitebase.contentful.view_builder
            - %contenful_space_name4life_landingpage%

    dothiv.shop.genitivfy:
        class: %dothiv.shop.genitivfy.class%
