parameters:
    dothiv.charity.service.mailer.domain_registered.class: Dothiv\CharityWebsiteBundle\Service\Mailer\DomainRegisteredMailer
    dothiv.charity.service.mailer.login.class: Dothiv\CharityWebsiteBundle\Service\Mailer\LoginLinkMailer

services:
    dothiv.charity.web.controller.app:
        class: Dothiv\CharityWebsiteBundle\Controller\AppController
        arguments:
          - @templating
          - "DothivCharityWebsiteBundle"

    dothiv.charity.service.mailer.domain_registered:
        class: %dothiv.charity.service.mailer.domain_registered.class%
        arguments:
        - @mailer
        - @router
        - @dothiv.businessbundle.service.user
        - @dothiv.charity.contentful.charity_content
        - %email_from_address%
        - %email_from_name%
        tags:
            - { name: kernel.event_listener, event: dothiv.business.domain.registered, method: onDomainRegistered }

    dothiv.charity.service.mailer.login:
        class: %dothiv.charity.service.mailer.login.class%
        arguments:
        - @mailer
        - @router
        - @dothiv.businessbundle.service.user
        - @dothiv.charity.contentful.charity_content
        - %email_from_address%
        - %email_from_name%
        tags:
            - { name: kernel.event_listener, event: dothiv.business.user.loginlink.requested, method: onLoginLinkRequested }
