services:
    dothiv.charity.web.controller.index:
        class: Dothiv\CharityWebsiteBundle\Controller\IndexController
        arguments:
          - @dothiv.websitebase.cache.request_lastmodified
          - @templating
          - @dothiv.charity.contentful.charity_content
          - "DothivCharityWebsiteBundle"
          - @clock
          - %page_lifetime%

    dothiv.charity.web.controller.projects:
        class: Dothiv\CharityWebsiteBundle\Controller\ProjectsController
        arguments:
          - @dothiv.websitebase.cache.request_lastmodified
          - @templating
          - @dothiv.charity.contentful.charity_content
          - "DothivCharityWebsiteBundle"
          - @clock
          - %page_lifetime%

    dothiv.charity.web.controller.page:
        class: Dothiv\CharityWebsiteBundle\Controller\PageController
        arguments:
          - @dothiv.websitebase.cache.request_lastmodified
          - @templating
          - @dothiv.charity.contentful.charity_content
          - "DothivCharityWebsiteBundle"
          - @clock
          - %page_lifetime%

    dothiv.charity.web.controller.app:
        class: Dothiv\BaseWebsiteBundle\Controller\AppController
        arguments:
          - @dothiv.websitebase.cache.request_lastmodified
          - @templating
          - @dothiv.charity.contentful.charity_content
          - "DothivCharityWebsiteBundle"
          - @clock
          - %page_lifetime%

    dothiv.charity.web.controller.contentful:
        class: Dothiv\CharityWebsiteBundle\Controller\ContentfulController
        arguments:
          - @dothiv.charity.contentful.charity_content

    dothiv.charity.web.controller.iframe:
        class: Dothiv\CharityWebsiteBundle\Controller\IframeController
        arguments:
          - @dothiv.repository.domain
          - @dothiv.websitebase.cache.request_lastmodified
          - @templating
          - @clock
          - %page_lifetime%
