services:
    dothiv.charity.web.controller.projects:
        class: Dothiv\CharityWebsiteBundle\Controller\ProjectsController
        arguments:
          - @dothiv.websitebase.cache.request_lastmodified
          - @templating
          - @dothiv.charity.contentful.charity_content
          - "DothivCharityWebsiteBundle"
          - @clock
          - %page_lifetime%

    dothiv.charity.web.controller.page:
        class: Dothiv\CharityWebsiteBundle\Controller\PageController
        arguments:
          - @dothiv.websitebase.cache.request_lastmodified
          - @templating
          - @dothiv.charity.contentful.charity_content
          - "DothivCharityWebsiteBundle"
          - @clock
          - %page_lifetime%

    dothiv.charity.web.controller.app:
        class: Dothiv\BaseWebsiteBundle\Controller\AppController
        arguments:
          - @dothiv.websitebase.cache.request_lastmodified
          - @templating
          - @dothiv.charity.contentful.charity_content
          - "DothivCharityWebsiteBundle"
          - @clock
          - %page_lifetime%

    dothiv.charity.web.controller.contentful:
        class: Dothiv\CharityWebsiteBundle\Controller\ContentfulController
        arguments:
          - @dothiv.charity.contentful.charity_content

    dothiv.charity.web.controller.social_board:
        class: Dothiv\CharityWebsiteBundle\Controller\SocialBoardController
        arguments:
          - %twitter_consumer_key%
          - %twitter_consumer_secret%
          - %twitter_oauth_access_token%
          - %twitter_oauth_access_token_secret%
          - @clock
          - 600

    dothiv.charity.web.controller.browserplugin:
        class: Dothiv\CharityWebsiteBundle\Controller\BrowserPluginController
        arguments:
          - @dothiv.websitebase.cache.request_lastmodified
          - @templating
          - @dothiv.charity.contentful.charity_content
          - "DothivCharityWebsiteBundle"
          - @clock
          - %page_lifetime%
        calls:
        - [setDomainRepository, [@dothiv.repository.domain]]
