services:
    dothiv.charity.web.contentful.project_image_listener:
        class: %dothiv.base.web.contentul.image_listener.class%
        arguments:
            - @dothiv.websitebase.contentful.image_scaler
            - 'Project'
            - 'images'
        tags:
            - { name: dothiv.business.event_listener, event: dothiv.basewebsite.contentful.view.create, method: onViewCreate }

    dothiv.charity.web.contentful.pressquote_logo_listener:
        class: %dothiv.base.web.contentul.image_listener.class%
        arguments:
            - @dothiv.websitebase.contentful.image_scaler
            - 'PressQuote'
            - 'logo'
        tags:
            - { name: dothiv.business.event_listener, event: dothiv.basewebsite.contentful.view.create, method: onViewCreate }

    dothiv.charity.web.contentful.hivdomain_logo_listener:
        class: %dothiv.base.web.contentul.image_listener.class%
        arguments:
            - @dothiv.websitebase.contentful.image_scaler
            - 'hivDomain'
            - 'logo'
        tags:
            - { name: dothiv.business.event_listener, event: dothiv.basewebsite.contentful.view.create, method: onViewCreate }
