services:
    dothiv.charity.web.controller.pinkbar:
        class: Dothiv\CharityWebsiteBundle\Controller\PinkbarController
        arguments:
          - @translator
          - @dothiv.websitebase.money_format
          - @dothiv.repository.config
          - @serializer
          - %eur_goal%
          - %already_donated%
          - %eur_increment%
          - @clock
          - %page_lifetime%
