parameters:
    dothiv.charity.service.mailer.domain_registered.class: Dothiv\CharityWebsiteBundle\Service\Mailer\DomainRegisteredMailer
    dothiv.charity.service.mailer.login.class: Dothiv\BaseWebsiteBundle\Service\Mailer\LoginLinkMailer
    dothiv.charity.service.mailer.content.class: Dothiv\BaseWebsiteBundle\Service\Mailer\ContentMailer

services:
    dothiv.charity.service.mailer.content:
        class: %dothiv.charity.service.mailer.content.class%
        arguments:
        - @mailer
        - @dothiv.charity.contentful.charity_content
        - %email_from_address%
        - %email_from_name%

    dothiv.charity.service.mailer.domain_registered:
        class: %dothiv.charity.service.mailer.domain_registered.class%
        arguments:
        - @dothiv.charity.service.mailer.content
        - @router
        - @dothiv.businessbundle.service.user
        - @dothiv.repository.domain
        - @clock
        tags:
            - { name: kernel.event_listener, event: dothiv.business.domain.registered, method: onDomainRegistered }
            - { name: kernel.event_listener, event: dothiv.business.domain.claim_token_requested, method: onDomainRegistered }

    dothiv.charity.service.mailer.login:
        class: %dothiv.charity.service.mailer.login.class%
        arguments:
        - @dothiv.charity.service.mailer.content
        - @router
        - 'dothiv_charity_account_index'
        - %charitydomain%
        - @dothiv.businessbundle.service.user
        tags:
            - { name: kernel.event_listener, event: dothiv.business.user.loginlink.requested, method: onLoginLinkRequested }
