parameters:
    dothiv.repository.domain_configuration_notification.entity.class: 'DothivCharityWebsiteBundle:DomainNotification'
    dothiv.repository.domain_configuration_notification.repository.class: Dothiv\CharityWebsiteBundle\Repository\DomainNotificationRepository

services:
    dothiv.repository.domain_configuration_notification:
        class: %dothiv.repository.domain_configuration_notification.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ %dothiv.repository.domain_configuration_notification.entity.class% ]
        calls:
        - [setValidator, ["@validator"]]
