parameters:
    dothiv.charity.routing.loader.class: Dothiv\CharityWebsiteBundle\Routing\RoutingLoader
    dothiv.charity.clickcounter_notification.class: Dothiv\CharityWebsiteBundle\Service\ClickCounterConfigurationService
    dothiv.charity.clickcounter_notification.mailer.class: Dothiv\CharityWebsiteBundle\Service\Mailer\DomainConfigurationMailer

services:
    dothiv.charity.routing.loader:
        class: %dothiv.charity.routing.loader.class%
        arguments:
         - %dothiv_charity_website.features%
        tags:
         - { name: routing.loader }

    dothiv.charity.translation.strings_loader:
        class: Dothiv\BaseWebsiteBundle\Translation\ContentfulStringsLoader
        arguments:
         - @dothiv.charity.contentful.charity_content
         - 'String'
         - 'ky'
        tags:
         - { name: translation.loader, alias: contentful_strings_charity }

    dothiv.charity.contentful.charity_content:
        class: %dothiv.websitebase.contentful.content.class%
        arguments:
            - @dothiv_contentful.content
            - @dothiv.websitebase.contentful.view_builder
            - %contenful_space_charity%

    dothiv.charity.clickcounter_notification.mailer:
        class: %dothiv.charity.clickcounter_notification.mailer.class%
        arguments:
        - @mailer
        - @dothiv.charity.contentful.charity_content
        - @dothiv_contentful.asset
        - @dothiv_contentful.repo.asset
        - %registry_email_from_address%
        - %registry_email_from_name%

    dothiv.charity.clickcounter_notification:
        class: %dothiv.charity.clickcounter_notification.class%
        arguments:
        - @dothiv.repository.domain
        - @dothiv.repository.domain_configuration_notification
        - @dothiv.charity.clickcounter_notification.mailer
