services:
    dothiv.qlp.controller.landingpage:
        class: Dothiv\QLPPartnerBundle\Controller\LandingPageController
        arguments:
          - @dothiv.websitebase.cache.request_lastmodified
          - @templating
          - @dothiv.charity.contentful.charity_content
          - "DothivQLPPartnerBundle"
          - @clock
          - %page_lifetime%
