parameters:
    dothiv.repository.banner.entity.class: 'DothivBusinessBundle:Banner'
    dothiv.repository.user.entity.class: 'DothivBusinessBundle:User'
    dothiv.repository.user.repository.class: Dothiv\BusinessBundle\Repository\UserRepository
    dothiv.repository.user_token.entity.class: 'DothivBusinessBundle:UserToken'
    dothiv.repository.user_token.repository.class: Dothiv\BusinessBundle\Repository\UserTokenRepository
    dothiv.repository.domain.entity.class: 'DothivBusinessBundle:Domain'
    dothiv.repository.domain.repository.class: Dothiv\BusinessBundle\Repository\DomainRepository
    dothiv.repository.banner.entity.class: 'DothivBusinessBundle:Banner'
    dothiv.repository.banner.repository.class: Dothiv\BusinessBundle\Repository\BannerRepository
    dothiv.repository.domainclaim.entity.class: 'DothivBusinessBundle:DomainClaim'
    dothiv.repository.domainclaim.repository.class: Dothiv\BusinessBundle\Repository\DomainClaimRepository
    dothiv.repository.attachment.entity.class: 'DothivBusinessBundle:Attachment'
    dothiv.repository.attachment.repository.class: Dothiv\BusinessBundle\Repository\AttachmentRepository
    dothiv.repository.nonprofitregistration.entity.class: 'DothivBusinessBundle:NonProfitRegistration'
    dothiv.repository.nonprofitregistration.repository.class: Dothiv\BusinessBundle\Repository\NonProfitRegistrationRepository
    dothiv.repository.premiumbid.entity.class: 'DothivBusinessBundle:PremiumBid'
    dothiv.repository.premiumbid.repository.class: Dothiv\BusinessBundle\Repository\PremiumBidRepository
    dothiv.repository.config.entity.class: 'DothivBusinessBundle:Config'
    dothiv.repository.config.repository.class: Dothiv\BusinessBundle\Repository\ConfigRepository
    dothiv.repository.registrar.entity.class: 'DothivBusinessBundle:Registrar'
    dothiv.repository.registrar.repository.class: Dothiv\BusinessBundle\Repository\RegistrarRepository
    dothiv.repository.invoice.entity.class: 'DothivBusinessBundle:Invoice'
    dothiv.repository.invoice.repository.class: Dothiv\BusinessBundle\Repository\InvoiceRepository
    dothiv.repository.user_notification.entity.class: 'DothivBusinessBundle:UserNotification'
    dothiv.repository.user_notification.repository.class: Dothiv\BusinessBundle\Repository\UserNotificationRepository
    dothiv.repository.entity_change.entity: 'DothivBusinessBundle:EntityChange'
    dothiv.repository.entity_change.repository.class: Dothiv\BusinessBundle\Repository\EntityChangeRepository
    dothiv.repository.user_profile_change.entity: 'DothivBusinessBundle:UserProfileChange'
    dothiv.repository.user_profile_change.repository.class: Dothiv\BusinessBundle\Repository\UserProfileChangeRepository
    dothiv.repository.domain_collaborator.entity: 'DothivBusinessBundle:DomainCollaborator'
    dothiv.repository.domain_collaborator.repository.class: Dothiv\BusinessBundle\Repository\DomainCollaboratorRepository

services:
    dothiv.repository.banner:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ %dothiv.repository.banner.entity.class% ]
        calls:
        - [setValidator, ["@validator"]]

    dothiv.repository.user:
        class: %dothiv.repository.user.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ %dothiv.repository.user.entity.class% ]
        calls:
        - [setValidator, ["@validator"]]

    dothiv.repository.user_token:
        class: %dothiv.repository.user_token.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ %dothiv.repository.user_token.entity.class% ]
        calls:
        - [setValidator, ["@validator"]]

    dothiv.repository.domain:
        class: %dothiv.repository.domain.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ %dothiv.repository.domain.entity.class% ]
        calls:
        - [setValidator, ["@validator"]]

    dothiv.repository.banner:
        class: %dothiv.repository.banner.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ %dothiv.repository.banner.entity.class% ]
        calls:
        - [setValidator, ["@validator"]]

    dothiv.repository.domainclaim:
        class: %dothiv.repository.domainclaim.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ %dothiv.repository.domainclaim.entity.class% ]
        calls:
        - [setValidator, ["@validator"]]

    dothiv.repository.attachment:
        class: %dothiv.repository.attachment.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ %dothiv.repository.attachment.entity.class% ]
        calls:
        - [setValidator, ["@validator"]]

    dothiv.repository.nonprofitregistration:
        class: %dothiv.repository.nonprofitregistration.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ %dothiv.repository.nonprofitregistration.entity.class% ]
        calls:
        - [setValidator, ["@validator"]]

    dothiv.repository.premiumbid:
        class: %dothiv.repository.premiumbid.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ %dothiv.repository.premiumbid.entity.class% ]
        calls:
        - [setValidator, ["@validator"]]

    dothiv.repository.config:
        class: %dothiv.repository.config.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ %dothiv.repository.config.entity.class% ]
        calls:
        - [setValidator, ["@validator"]]

    dothiv.repository.registrar:
        class: %dothiv.repository.registrar.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ %dothiv.repository.registrar.entity.class% ]
        calls:
        - [setValidator, ["@validator"]]

    dothiv.repository.invoice:
        class: %dothiv.repository.invoice.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ %dothiv.repository.invoice.entity.class% ]
        calls:
        - [setValidator, ["@validator"]]

    dothiv.repository.user_notification:
        class: %dothiv.repository.user_notification.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ %dothiv.repository.user_notification.entity.class% ]
        calls:
        - [setValidator, ["@validator"]]

    dothiv.repository.entity_change:
        class: %dothiv.repository.entity_change.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ %dothiv.repository.entity_change.entity% ]
        calls:
        - [setValidator, ["@validator"]]
        - [setEventDispatcher, ["@dothiv.business.event_dispatcher"]]

    dothiv.repository.user_profile_change:
        class: %dothiv.repository.user_profile_change.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ %dothiv.repository.user_profile_change.entity% ]
        calls:
        - [setValidator, ["@validator"]]

    dothiv.repository.domain_collaborator:
        class: %dothiv.repository.domain_collaborator.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ %dothiv.repository.domain_collaborator.entity% ]
        calls:
        - [setValidator, ["@validator"]]
