parameters:
    clickcounter.class: Dothiv\BusinessBundle\Service\ClickCounterConfig
    dothiv.businessbundle.service.clock.class: Dothiv\ValueObject\ClockValue
    dothiv.businessbundle.service.user.class: Dothiv\BusinessBundle\Service\UserService
    dothiv.businessbundle.service.attachment.class: Dothiv\BusinessBundle\Service\AttachmentService
    dothiv.businessbundle.service.attachment_store.class: Dothiv\BusinessBundle\Service\AttachmentStoreService
    registration.class: Dothiv\BusinessBundle\Service\Registration
    dothiv.business.service.nonprofitregistration.class: Dothiv\BusinessBundle\Service\NonprofitRegistrationService

services:
    clickcounter:
        class: %clickcounter.class%
        arguments:
        - %dothiv_business.clickcounter%
        - @dothiv.business.contentful.clickcounter_content
        - @dothiv.business.event_dispatcher

    registration:
        class: %registration.class%
        arguments:
        - @event_dispatcher
        - @dothiv.repository.domain
        - @dothiv.repository.registrar

    clock:
        class: %dothiv.businessbundle.service.clock.class%
        arguments:
        - %dothiv_business.clock_expr%
        - @event_dispatcher

    dothiv.businessbundle.service.user:
        class: %dothiv.businessbundle.service.user.class%
        arguments:
        - @dothiv.repository.user
        - @dothiv.repository.user_token
        - @clock
        - @event_dispatcher
        - 'dothiv.business.user.loginlink.requested'
        - "%charitydomain%"
        - %dothiv_business.link_request_wait%

    dothiv.businessbundle.service.attachment:
        class: %dothiv.businessbundle.service.attachment.class%
        arguments:
        - @dothiv.repository.attachment
        - ['application/pdf']
        - @dothiv.businessbundle.service.attachment_store

    dothiv.businessbundle.service.attachment_store:
        class: %dothiv.businessbundle.service.attachment_store.class%
        arguments:
        - %dothiv_business.attachments_location%

    dothiv.business.contentful.clickcounter_content:
        class: %dothiv.websitebase.contentful.content.class%
        arguments:
            - @dothiv_contentful.content
            - @dothiv.websitebase.contentful.view_builder
            - %contenful_space_clickcounter%

    dothiv.business.service.nonprofitregistration:
        class: %dothiv.business.service.nonprofitregistration.class%
        arguments:
        - @dothiv.repository.nonprofitregistration

    dothiv.business.event_dispatcher:
        class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
        arguments:
            - @service_container
