## Domain collaborator API
dothiv_api_domain_collaborator:
    pattern:  /api/domain/{domain}/collaborator/{identifier}
    defaults:
        _controller: dothiv.api.controller.domain_collaborator:getItemAction
        _format: json
    methods: [GET]

dothiv_api_domain_collaborator_create:
    pattern:  /api/domain/{domain}/collaborator
    defaults:
        _controller: dothiv.api.controller.domain_collaborator:createItemAction
        _format: json
        _dothiv.ApiRequest: \Dothiv\APIBundle\Request\DomainCollaboratorCreateRequest
    methods: [POST]

dothiv_api_domain_collaborator_delete:
    pattern:  /api/domain/{domain}/collaborator/{identifier}
    defaults:
        _controller: dothiv.api.controller.domain_collaborator:deleteItemAction
        _format: json
    methods: [DELETE]

dothiv_api_domain_collaborator_list:
    pattern:  /api/domain/{domain}/collaborator
    defaults:
        _controller: dothiv.api.controller.domain_collaborator:listItemsAction
        _format: json
    methods: [GET]
