# Redirect to default locale: en
dothiv_charity_index_nolang:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /en
        permanent: true

dothiv_charity_index:
    pattern:  /{locale}
    defaults:
        _controller: dothiv.charity.web.controller.page:pageAction
        page: home
    requirements:
        locale:  en|de|ky

dothiv_charity_app_template:
    pattern:  /{locale}/app/{section}/{page}.{_format}
    defaults:
        _controller: dothiv.charity.web.controller.app:templateAction
    requirements:
        _format:  html
        locale:  en|de|ky

dothiv_charity_content_api:
    pattern:  /{locale}/content/{type}
    defaults:
        _controller: dothiv.charity.web.controller.page:contentAction
    requirements:
        locale:  en|de
        _format: json
        type: Quote|hivDomain|PressQuote

dothiv_charity_clickstart:
    pattern:  /{locale}/clickstart/{page}
    defaults:
        _controller: dothiv.charity.web.controller.page:pageAction
        type: Block
        template: :Page/clickstart
    requirements:
        locale: en|de|ky

dothiv_charity_about_index:
    pattern:  /{locale}/p/about/mission
    defaults:
        _controller: dothiv.charity.web.controller.page:pageAction
        page: about/mission
        navigation: nav.about
    requirements:
        locale: en|de|ky

dothiv_charity_about:
    pattern:  /{locale}/p/about/{page}
    defaults:
        _controller: dothiv.charity.web.controller.page:aboutPageAction
        navigation: nav.about
    requirements:
        locale: en|de|ky
        page: ^([a-zA-Z][a-zA-Z0-9]*[/-])*[a-zA-Z][a-zA-Z0-9]*$

dothiv_charity_page:
    pattern:  /{locale}/p/{page}
    defaults:
        _controller: dothiv.charity.web.controller.page:pageAction
    requirements:
        locale:  en|de|ky
        page: ^([a-zA-Z][a-zA-Z0-9]*[/-])*[a-zA-Z][a-zA-Z0-9]*$

dothiv_charity_content:
    pattern:  /{locale}/c/{page}
    defaults:
        _controller: dothiv.charity.web.controller.page:contentPageAction
    requirements:
        locale:  en|de|ky
        page: ^([a-zA-Z][a-zA-Z0-9]*[/-])*[a-zA-Z][a-zA-Z0-9]*$

# Contentful
dothiv_charity_strings:
    pattern:  /contentful/strings
    defaults:
        _controller: dothiv.charity.web.controller.contentful:stringsAction
